/* Field workflow: object -> room -> measured quantity -> estimate. */
(() => {
  let selected = null;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const val = (form, name) => (form.elements?.[name]||form.querySelector?.(`[name="${name}"]`))?.value?.trim() || '';
  const send = (path, data) => api(path, {method:'POST', body:JSON.stringify(data)});
  const money = kopecks => new Intl.NumberFormat('ru-RU', {style:'currency', currency:'RUB'}).format((kopecks || 0) / 100);
  const number = value => Number(String(value).replace(',', '.'));
  const today = () => {const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`};
  const field = (name, label, type='text', extra='') => `<label><span>${label}</span><input name="${name}" type="${type}" ${extra}></label>`;
  const options = (items, selectedId='') => items.map(item => `<option value="${esc(item.id)}" ${item.id===selectedId?'selected':''}>${esc(item.name)}</option>`).join('');
  const changeLine = (item={}) => `<div class="construction-change-line"><input aria-label="Работа" name="name" required maxlength="200" placeholder="Дополнительная работа" value="${esc(item.name||'')}"><input aria-label="Количество" name="quantity" type="number" required min="0.0001" step="any" placeholder="Кол-во" value="${esc(item.quantity||'')}"><select aria-label="Единица" name="unit">${['шт.','м²','м³','м','м.п.','компл.','л','кг','ч'].map(unit=>`<option value="${esc(unit)}" ${item.unit===unit?'selected':''}>${esc(unit)}</option>`).join('')}</select><input aria-label="Цена за единицу, ₽" name="price" type="number" required min="0" step="0.01" placeholder="Цена, ₽" value="${item.unit_price!=null?esc(item.unit_price/100):''}"><button type="button" class="construction-edit" data-change-remove aria-label="Удалить позицию">Удалить</button></div>`;
  const kinds = {work:'Работа',material:'Материал',equipment:'Оборудование',service:'Услуга',other:'Прочее'};
  async function request(path, data, after, method='POST') {
    try { await api(path, {method, body:JSON.stringify(data)}); await after(); }
    catch (error) { notify(error.message); }
  }
  async function list() {
    const result = await api('/construction/objects');
    view(`<div class="topline"><div><span class="eyebrow">СТРОИТЕЛЬНЫЙ РЕЖИМ</span><h1>Объекты и замеры</h1><p class="muted">От размеров помещения до сметы и контроля выполнения.</p></div></div>
      <section class="construction-intro"><div><strong>Новый объект</strong><small>Обычные сметы остаются доступны отдельно.</small></div><form id="construction-new" class="construction-inline">${field('name','Название объекта','text','required maxlength="200" placeholder="Квартира на Лесной"')}<button class="btn primary">Создать объект</button></form></section>
      <section class="construction-list"><div class="construction-section-title"><h2>В работе</h2><span>${result.items.length}</span></div>${result.items.length?result.items.map(item=>`<button class="construction-object" data-id="${esc(item.id)}"><span><strong>${esc(item.name)}</strong><small>${esc(item.description || 'Замеры, объёмы и смета')}</small></span><span class="construction-object-right">${item.project_id?'Заказ в работе':item.quote_id?'Смета создана':'Замеры'} <b>↗</b></span></button>`).join(''):'<p class="construction-empty">Создайте объект и добавьте первое помещение.</p>'}</section>`);
    document.querySelector('#construction-new').onsubmit = event => {event.preventDefault();const form=event.currentTarget;request('/construction/objects',{name:val(form,'name')},async()=>{const objects=await api('/construction/objects');selected=objects.items[0]?.id;await detail()})};
    document.querySelectorAll('.construction-object').forEach(button => button.onclick=()=>{selected=button.dataset.id;detail()});
  }
  async function detail() {
    const [data,supplierData] = await Promise.all([api('/construction/objects/' + encodeURIComponent(selected)),api('/construction/suppliers')]);
    const obj=data.object, zones=data.zones, rows=data.quantities, logs=data.daily_logs||[], suppliers=supplierData.items||[], purchases=data.purchases||[], changes=data.changes||[];
    view(`<div class="construction-back"><button id="construction-back" type="button">← Все объекты</button><span>ОБЪЕКТ / ${esc(obj.status.toUpperCase())}</span></div>
      <div class="topline construction-heading"><div><h1>${esc(obj.name)}</h1><p class="muted">${esc(obj.description || 'Добавьте размеры помещений, затем работы и материалы.')}</p></div><div class="topline-actions"><label class="btn small construction-import" title="Помещения в XLSX должны совпадать с помещениями объекта">Импорт XLSX<input id="construction-import" type="file" accept=".xlsx" hidden></label><button id="construction-export" class="btn small">Скачать XLSX</button>${obj.project_id?`<button id="construction-project-open" class="btn small">Открыть заказ ↗</button>`:''}${obj.quote_id?`<button id="construction-quote-open" class="btn primary">Открыть смету ↗</button>`:`<button id="construction-quote" class="btn primary" ${rows.length?'':'disabled'}>Создать смету ↗</button>`}</div></div>
      <div class="construction-metrics"><div><span>План</span><strong>${money(data.totals.planned_kopecks)}</strong></div><div><span>Факт по позициям</span><strong>${money(data.totals.actual_kopecks)}</strong></div><div><span>Себестоимость</span><strong>${money(data.totals.cost_kopecks)}</strong></div></div>
      <section class="construction-section"><div class="construction-section-title"><h2>01 / Помещения</h2><span>${zones.length}</span></div><form id="construction-zone" class="construction-inline">${field('name','Название','text','required placeholder="Кухня" maxlength="120"')}${field('length','Длина, м','number','required min="0.001" step="any" placeholder="5"')}${field('width','Ширина, м','number','required min="0.001" step="any" placeholder="4"')}${field('height','Высота, м','number','min="0" step="any" placeholder="2.8"')}<button class="btn">Добавить помещение</button></form>
      ${zones.length?zones.map(zone=>`<div class="construction-row"><strong>${esc(zone.name)}</strong><span>${esc(zone.length_m)} × ${esc(zone.width_m)} м</span><b>${(number(zone.length_m)*number(zone.width_m)).toLocaleString('ru-RU')} м²</b><button type="button" class="construction-edit" data-zone-edit="${esc(zone.id)}">Изменить</button></div>`).join(''):'<p class="construction-empty">Помещений пока нет. Их размеры станут переменными для расчёта.</p>'}
      <form id="construction-measurement" class="construction-inline construction-subform"><label><span>Помещение</span><select name="zone_id" required><option value="">Выберите</option>${options(zones)}</select></label>${field('symbol','Переменная','text','required pattern="[a-z][a-z0-9_]{1,31}" placeholder="window_area"')}${field('value','Замер','number','required min="0" step="any" placeholder="1.5"')}<label><span>Единица</span><select name="unit"><option value="м²">м²</option><option value="м">м</option><option value="см">см</option><option value="шт.">шт.</option></select></label><button class="btn">Записать замер</button></form>
      ${data.measurements.map(item=>`<div class="construction-row"><strong>${esc(item.symbol)}</strong><span>${esc(zones.find(zone=>zone.id===item.zone_id)?.name||'Объект')}</span><b>${esc(item.value)} ${esc(item.unit)}</b><button type="button" class="construction-edit" data-measure-edit="${esc(item.id)}">Изменить</button></div>`).join('')}</section>
      <section class="construction-section"><div class="construction-section-title"><h2>02 / Ведомость объёмов</h2><span>${rows.length}</span></div><form id="construction-quantity" class="construction-inline construction-quantity-form"><label><span>Помещение</span><select name="zone_id" required><option value="">Выберите</option>${options(zones)}</select></label><label><span>Тип</span><select name="kind"><option value="work">Работа</option><option value="material">Материал</option><option value="equipment">Оборудование</option></select></label>${field('title','Наименование','text','required maxlength="200" placeholder="Покраска стен"')}${field('formula','Формула объёма','text','required value="area" maxlength="160"')}${field('unit_price','Цена за ед., ₽','number','min="0" step="0.01" value="0"')}${field('price_coefficient','Коэфф. цены','number','min="0.001" max="100" step="any" value="1"')}${field('markup_percent','Наценка, %','number','min="0" max="1000" step="any" value="0"')}${field('discount_percent','Скидка, %','number','min="0" max="100" step="any" value="0"')}${field('coefficient_reason','Причина коэффициента','text','maxlength="500" placeholder="Сложная поверхность"')}<button class="btn">Рассчитать и добавить</button></form>
      <p class="construction-hint">Формула использует длину, ширину и высоту помещения: <code>area</code>, <code>perimeter * height - openings</code>, <code>volume</code>. Для материала укажите расход на единицу работы ниже.</p>
      ${rows.length?`<div class="construction-table"><div class="construction-table-head"><span>Позиция</span><span>Объём</span><span>План</span><span>Факт</span></div>${rows.map(item=>`<div class="construction-table-row"><span class="construction-price-name"><input type="checkbox" class="construction-price-select" value="${esc(item.id)}" aria-label="Выбрать ${esc(item.title)}"><span><strong>${esc(item.title)}</strong><small>${esc(kinds[item.kind]||item.kind)} · ${esc(item.formula)} <button type="button" class="construction-edit" ${item.kind==='material'?'data-material-edit':'data-quantity-edit'}="${esc(item.id)}">Изменить</button></small></span></span><span>${esc(item.quantity)} ${esc(item.unit)}</span><span>${money(item.planned_total_kopecks)}</span><span>${esc(item.actual_quantity)} ${esc(item.unit)}</span></div>`).join('')}</div><form id="construction-prices" class="construction-price-tools"><div class="construction-price-heading"><div><strong>Изменить расценки</strong><span id="construction-price-count">Выберите позиции</span></div><button type="button" class="construction-edit" id="construction-price-all">${rows.length>50?'Выбрать первые 50':'Выбрать все'}</button></div><div class="construction-price-controls"><label><span>Изменение, %</span><input name="percent" type="number" min="-100" max="1000" step="0.01" value="8" required aria-label="Изменение цены в процентах"></label><button class="btn" type="submit">Показать изменения</button></div><div id="construction-price-preview" aria-live="polite"></div>${data.latest_price_batch && !data.latest_price_batch.undone_at && data.latest_price_batch.created_at>Date.now()/1000-7*86400?`<div class="construction-price-undo"><span>Последнее изменение расценок</span><button type="button" id="construction-price-undo" class="construction-edit">Отменить изменение</button></div>`:''}</form><form id="construction-fact" class="construction-inline construction-subform"><label><span>Выполненная позиция</span><select name="quantity_id" required>${rows.map(item=>`<option value="${esc(item.id)}">${esc(item.title)}</option>`).join('')}</select></label>${field('quantity','Фактический объём','number','required min="0.0001" step="any" placeholder="8"')}<button class="btn">Записать факт</button></form>`:'<p class="construction-empty">Добавьте работу. Объём рассчитается из реальных размеров.</p>'}
      </section><section class="construction-section"><div class="construction-section-title"><h2>03 / Материалы по норме</h2></div><form id="construction-material" class="construction-inline"><label><span>Работа</span><select name="parent_work_id" required><option value="">Выберите</option>${rows.filter(row=>row.kind==='work').map(row=>`<option value="${esc(row.id)}">${esc(row.title)} · ${esc(row.quantity)} ${esc(row.unit)}</option>`).join('')}</select></label>${field('title','Материал','text','required placeholder="Краска" maxlength="200"')}${field('consumption_rate','Расход на ед.','number','required min="0.0001" step="any" placeholder="0.2"')}${field('waste_percent','Запас, %','number','min="0" max="100" step="any" value="0"')}${field('unit_price','Цена за ед., ₽','number','min="0" step="0.01" value="0"')}${field('price_coefficient','Коэфф. цены','number','min="0.001" max="100" step="any" value="1"')}${field('markup_percent','Наценка, %','number','min="0" max="1000" step="any" value="0"')}${field('discount_percent','Скидка, %','number','min="0" max="100" step="any" value="0"')}<button class="btn">Добавить материал</button></form></section>
      <section class="construction-section"><div class="construction-section-title"><h2>04 / Дефектная ведомость</h2><span>${data.defects.length}</span></div>
      <form id="construction-defect" class="construction-inline construction-defect-form"><label><span>Помещение</span><select name="zone_id"><option value="">Весь объект</option>${options(zones)}</select></label><label><span>Фото</span><select name="photo_file_id" id="construction-defect-photo"><option value="">Без фото</option></select></label><label><span>Важность</span><select name="severity"><option value="normal">Обычная</option><option value="low">Низкая</option><option value="high">Высокая</option></select></label>${field('description','Что обнаружено','text','required maxlength="2000" placeholder="Трещина на стене"')}${field('measurement_note','Замер','text','maxlength="500" placeholder="Длина 1,2 м"')}${field('suggested_work','Предлагаемая работа','text','maxlength="500" placeholder="Заделка трещины"')}<button class="btn">Добавить дефект</button></form>
      ${data.defects.length?data.defects.map(item=>`<div class="construction-row construction-defect-row"><strong>${esc(item.description)}</strong><span>${esc(zones.find(zone=>zone.id===item.zone_id)?.name||'Весь объект')}${item.measurement_note?' · '+esc(item.measurement_note):''}${item.suggested_work?' · '+esc(item.suggested_work):''}</span><select aria-label="Статус дефекта" data-defect-status="${esc(item.id)}"><option value="open" ${item.status==='open'?'selected':''}>Открыт</option><option value="in_progress" ${item.status==='in_progress'?'selected':''}>В работе</option><option value="resolved" ${item.status==='resolved'?'selected':''}>Устранён</option></select>${item.photo_file_id?`<button type="button" class="construction-edit" data-defect-photo="${esc(item.photo_file_id)}">Фото ↗</button>`:''}</div>`).join(''):'<p class="construction-empty">Дефектов пока нет. Зафиксируйте проблему и прикрепите фото ниже.</p>'}</section>
      <section class="construction-section"><div class="construction-section-title"><h2>05 / Журнал работ</h2><span>${logs.length}</span></div>
      <form id="construction-log" class="construction-inline construction-log-form">${field('work_date','Дата','date','required value="'+today()+'"')}<label><span>Помещение</span><select name="zone_id"><option value="">Весь объект</option>${options(zones)}</select></label><label><span>Позиция ведомости</span><select name="quantity_id"><option value="">Без привязки</option>${rows.filter(row=>row.kind==='work').map(row=>`<option value="${esc(row.id)}">${esc(row.title)} · ${esc(row.unit)}</option>`).join('')}</select></label>${field('work_description','Что сделали','text','required maxlength="2000" placeholder="Выполнили подготовку стен"')}${field('workers','Исполнители','text','maxlength="500" placeholder="Имена или бригада"')}${field('worker_count','Человек','number','min="0" max="100" value="0"')}${field('completed_quantity','Объём за день','number','min="0" max="1000000" step="any" value="0"')}<label><span>Единица</span><select name="unit"><option value="">Без объёма</option>${['м²','м³','м','м.п.','шт.','компл.','кг','т','л','ч','чел.-ч','маш.-ч'].map(unit=>`<option value="${esc(unit)}">${esc(unit)}</option>`).join('')}</select></label>${field('comment','Комментарий','text','maxlength="2000" placeholder="Что важно для следующей смены"')}<div class="construction-log-photos"><span>Фото записи · до 4</span><div id="construction-log-photo-options"></div></div><button class="btn">Записать день</button><button class="construction-edit" id="construction-log-cancel" type="button" hidden>Отменить изменение</button></form>
      ${logs.length?logs.map(item=>`<div class="construction-log-row"><div><span class="construction-log-date">${esc(item.work_date)}${item.worker_count?' · '+esc(item.worker_count)+' чел.':''}</span><strong>${esc(item.work_description)}</strong><small>${esc(zones.find(zone=>zone.id===item.zone_id)?.name||'Весь объект')}${item.workers?' · '+esc(item.workers):''}${Number(item.completed_quantity)?' · '+esc(item.completed_quantity)+' '+esc(item.unit):''}</small>${item.comment?`<p>${esc(item.comment)}</p>`:''}<div class="construction-log-photo-links">${(item.photo_file_ids||[]).map((fileId,index)=>`<button type="button" class="construction-edit" data-log-photo="${esc(fileId)}">Фото ${index+1} ↗</button>`).join('')}</div></div><div class="construction-log-actions"><button type="button" class="construction-edit" data-log-edit="${esc(item.id)}">Изменить</button><button type="button" class="construction-edit" data-log-delete="${esc(item.id)}">Удалить</button></div></div>`).join(''):'<p class="construction-empty">Запишите выполненные работы, людей и фотографии. Объём по позиции сразу попадёт в факт.</p>'}</section>
      <section class="construction-section"><div class="construction-section-title"><h2>06 / Закупки материалов</h2><span>${data.procurement.length} позиций</span></div>
      ${data.procurement.length?data.procurement.map(item=>`<div class="construction-procurement-row"><strong>${esc(item.title)}</strong><span>Нужно ${esc(item.required_quantity)} ${esc(item.unit)} · получено ${esc(item.received_quantity)}${Number(item.ordered_quantity)?' · заказано '+esc(item.ordered_quantity):''}</span><b>${Number(item.to_buy_quantity)>0?'Докупить '+esc(item.to_buy_quantity)+' '+esc(item.unit):'Закрыто'}</b>${Number(item.shortage_quantity)>0?`<em>Недостача ${esc(item.shortage_quantity)} ${esc(item.unit)}</em>`:''}</div>`).join(''):'<p class="construction-empty">Добавьте материалы по норме расхода — список закупки появится здесь автоматически.</p>'}
      <form id="construction-supplier" class="construction-inline construction-subform">${field('name','Новый поставщик','text','required maxlength="200" placeholder="Название"')}${field('phone','Телефон','tel','maxlength="50"')}${field('email','Email','email','maxlength="200"')}<button class="btn">Добавить поставщика</button></form>
      ${suppliers.length?`<p class="construction-hint">Поставщики: ${suppliers.map(item=>esc(item.name)).join(' · ')}</p>`:''}
      <form id="construction-purchase" class="construction-inline construction-subform"><label><span>Материал</span><select name="material_id" required><option value="">Выберите</option>${rows.filter(row=>row.kind==='material').map(row=>`<option value="${esc(row.id)}">${esc(row.title)} · ${esc(row.unit)}</option>`).join('')}</select></label><label><span>Поставщик</span><select name="supplier_id"><option value="">Не указан</option>${options(suppliers)}</select></label>${field('purchased_on','Дата','date','required value="'+today()+'"')}${field('quantity','Количество','number','required min="0.0001" step="any"')}${field('unit_price','Цена за единицу, ₽','number','min="0" step="0.01" value="0"')}<label><span>Статус</span><select name="status"><option value="ordered">Заказано</option><option value="received">Получено</option></select></label><label><span>Чек или накладная</span><select name="receipt_file_id" id="construction-purchase-receipt"><option value="">Без файла</option></select></label>${field('notes','Примечание','text','maxlength="2000"')}<button class="btn">Записать закупку</button><button class="construction-edit" id="construction-purchase-cancel" type="button" hidden>Отменить изменение</button></form>
      ${purchases.map(item=>`<div class="construction-procurement-row"><strong>${esc(rows.find(row=>row.id===item.material_id)?.title||'Материал')}</strong><span>${esc(item.purchased_on)} · ${esc(item.quantity)} ${esc(rows.find(row=>row.id===item.material_id)?.unit||'')} · ${money(Number(item.unit_price_kopecks)*Number(item.quantity))}${item.supplier_id?' · '+esc(suppliers.find(supplier=>supplier.id===item.supplier_id)?.name||'Поставщик'):''}</span><b>${item.status==='received'?'Получено':'Заказано'}</b><div class="construction-log-actions">${item.receipt_file_id?`<button type="button" class="construction-edit" data-purchase-receipt="${esc(item.receipt_file_id)}">Чек ↗</button>`:''}<button type="button" class="construction-edit" data-purchase-edit="${esc(item.id)}">Изменить</button><button type="button" class="construction-edit" data-purchase-delete="${esc(item.id)}">Удалить</button></div></div>`).join('')}</section>
      <section class="construction-section"><div class="construction-section-title"><h2>07 / Документы по объекту</h2></div><p class="construction-hint">Акт сохраняет фактические объёмы на момент создания. Отчёт показывает текущие работы, материалы, оплаты и фото без внутренних закупочных цен.</p><div class="construction-change-buttons"><button type="button" id="construction-act" class="btn" ${rows.some(row=>Number(row.actual_quantity)>0)?'':'disabled'}>Сформировать черновик акта ↗</button><button type="button" id="construction-report" class="btn">Скачать отчёт PDF ↗</button></div></section>
      <section class="construction-section"><div class="construction-section-title"><h2>08 / Дополнительные работы</h2><span>${changes.length} версий</span></div><p class="construction-hint">Допработы согласуются отдельно от основной сметы. После отправки состав и сумма версии не меняются.</p>
      <form id="construction-change" class="construction-change-form"><div class="construction-inline">${field('title','Название','text','required maxlength="200" placeholder="Дополнительные розетки"')}${field('deadline_days','Добавится к сроку, дней','number','min="0" max="365" value="0"')}${field('description','Описание для клиента','text','maxlength="2000"')}</div><div id="construction-change-lines">${changeLine()}</div><div class="construction-change-buttons"><button id="construction-change-add" type="button" class="construction-edit">+ Добавить позицию</button><button class="btn" type="submit">Сохранить черновик</button><button id="construction-change-cancel" type="button" class="construction-edit" hidden>Отменить изменение</button></div></form>
      ${changes.length?changes.map(item=>`<div class="construction-change-row"><div><small>ВЕРСИЯ ${esc(item.version)} · ${esc(({draft:'Черновик',sent:'На согласовании',approved:'Согласовано',changes_requested:'Нужны изменения',declined:'Отклонено'})[item.status]||item.status)}</small><strong>${esc(item.title)}</strong><span>${item.items.map(line=>esc(line.name)+' · '+esc(line.quantity)+' '+esc(line.unit)).join(' / ')}${item.response_comment?' · Ответ клиента: '+esc(item.response_comment):''}</span></div><b>${money(item.amount_kopecks)}</b><div class="construction-log-actions">${item.status==='draft'?`<button type="button" class="construction-edit" data-change-edit="${esc(item.id)}">Изменить</button><button type="button" class="construction-edit" data-change-send="${esc(item.id)}">Отправить клиенту</button><button type="button" class="construction-edit" data-change-delete="${esc(item.id)}">Удалить черновик</button>`:''}${item.status==='changes_requested'||item.status==='declined'?`<button type="button" class="construction-edit" data-change-revise="${esc(item.id)}">Новая версия</button>`:''}${item.public_token?`<button type="button" class="construction-edit" data-change-link="${esc(item.id)}">Скопировать ссылку ↗</button>`:''}${item.status==='sent'?`<button type="button" class="construction-edit" data-change-revoke="${esc(item.id)}">Отозвать ссылку</button>`:''}</div></div>`).join(''):'<p class="construction-empty">Когда появятся новые работы, добавьте их здесь и отправьте клиенту на отдельное согласование.</p>'}
      ${data.scope?.base_quote_kopecks!=null?`<p class="construction-hint">Основная смета ${money(data.scope.base_quote_kopecks)} · согласованные допработы ${money(data.scope.approved_changes_kopecks)} · вместе ${money(data.scope.current_total_kopecks)}</p>`:changes.some(item=>item.status==='approved')?`<p class="construction-hint">Согласованные допработы: ${money(data.scope.approved_changes_kopecks)}. Основная смета ещё не создана.</p>`:''}</section>
      <section class="construction-section"><div class="construction-section-title"><h2>09 / Фото и документы</h2><span id="construction-file-count"></span></div><label class="construction-upload">Прикрепить фото, PDF или TXT<input id="construction-file" type="file" accept="image/png,image/jpeg,application/pdf,text/plain" hidden></label><div id="construction-files"></div></section>`);
    document.querySelector('#construction-back').onclick=()=>{selected=null;list()};
    const zoneForm=document.querySelector('#construction-zone');zoneForm.onsubmit=event=>{event.preventDefault();const form=event.currentTarget;request(`/construction/objects/${selected}/zones${form.dataset.edit?'/'+form.dataset.edit:''}`,{name:val(form,'name'),length:val(form,'length'),width:val(form,'width'),height:val(form,'height')||0},detail,form.dataset.edit?'PATCH':'POST')};
    document.querySelectorAll('[data-zone-edit]').forEach(button=>button.onclick=()=>{const item=zones.find(zone=>zone.id===button.dataset.zoneEdit);zoneForm.dataset.edit=item.id;for(const [key,value] of Object.entries({name:item.name,length:item.length_m,width:item.width_m,height:item.height_m}))zoneForm.elements[key].value=value;zoneForm.querySelector('button').textContent='Сохранить размеры';zoneForm.scrollIntoView({behavior:'smooth',block:'center'})});
    const measureForm=document.querySelector('#construction-measurement');measureForm.onsubmit=event=>{event.preventDefault();const form=event.currentTarget;request(`/construction/objects/${selected}/measurements${form.dataset.edit?'/'+form.dataset.edit:''}`,{zone_id:val(form,'zone_id'),symbol:val(form,'symbol'),value:val(form,'value'),unit:val(form,'unit'),source:'manual'},detail,form.dataset.edit?'PATCH':'POST')};
    document.querySelectorAll('[data-measure-edit]').forEach(button=>button.onclick=()=>{const item=data.measurements.find(row=>row.id===button.dataset.measureEdit);measureForm.dataset.edit=item.id;for(const [key,value] of Object.entries({zone_id:item.zone_id,symbol:item.symbol,value:item.value,unit:item.unit}))measureForm.elements[key].value=value;measureForm.querySelector('button').textContent='Сохранить замер';measureForm.scrollIntoView({behavior:'smooth',block:'center'})});
    const quantityForm=document.querySelector('#construction-quantity');quantityForm.onsubmit=event=>{event.preventDefault();const form=event.currentTarget;const price=Math.round(number(val(form,'unit_price'))*100);const payload={zone_id:val(form,'zone_id'),kind:val(form,'kind'),title:val(form,'title'),formula:val(form,'formula'),unit_price:price,price_coefficient:val(form,'price_coefficient'),markup_percent:val(form,'markup_percent'),discount_percent:val(form,'discount_percent'),coefficient_reason:val(form,'coefficient_reason')};if(!form.dataset.edit)payload.unit='м²';request(`/construction/objects/${selected}/quantities${form.dataset.edit?'/'+form.dataset.edit:''}`,payload,detail,form.dataset.edit?'PATCH':'POST')};
    document.querySelectorAll('[data-quantity-edit]').forEach(button=>button.onclick=()=>{const item=rows.find(row=>row.id===button.dataset.quantityEdit);quantityForm.dataset.edit=item.id;for(const [key,value] of Object.entries({zone_id:item.zone_id,kind:item.kind,title:item.title,formula:item.formula,unit_price:item.unit_price/100,price_coefficient:item.price_coefficient,markup_percent:item.markup_percent,discount_percent:item.discount_percent,coefficient_reason:item.coefficient_reason}))if(quantityForm.elements[key])quantityForm.elements[key].value=value;quantityForm.querySelector('button').textContent='Пересчитать позицию';quantityForm.scrollIntoView({behavior:'smooth',block:'center'})});
    const materialForm=document.querySelector('#construction-material');materialForm.onsubmit=event=>{event.preventDefault();const form=event.currentTarget;const price=Math.round(number(val(form,'unit_price'))*100);const payload={title:val(form,'title'),consumption_rate:val(form,'consumption_rate'),waste_percent:val(form,'waste_percent')||0,unit_price:price,price_coefficient:val(form,'price_coefficient'),markup_percent:val(form,'markup_percent'),discount_percent:val(form,'discount_percent')};if(!form.dataset.edit)Object.assign(payload,{parent_work_id:val(form,'parent_work_id'),kind:'material',unit:'л'});request(`/construction/objects/${selected}/quantities${form.dataset.edit?'/'+form.dataset.edit:''}`,payload,detail,form.dataset.edit?'PATCH':'POST')};
    document.querySelectorAll('[data-material-edit]').forEach(button=>button.onclick=()=>{const item=rows.find(row=>row.id===button.dataset.materialEdit);materialForm.dataset.edit=item.id;for(const [key,value] of Object.entries({parent_work_id:item.parent_work_id,title:item.title,consumption_rate:item.consumption_rate,waste_percent:item.waste_percent,unit_price:item.unit_price/100,price_coefficient:item.price_coefficient,markup_percent:item.markup_percent,discount_percent:item.discount_percent}))materialForm.elements[key].value=value;materialForm.querySelector('button').textContent='Пересчитать материал';materialForm.scrollIntoView({behavior:'smooth',block:'center'})});
    const factForm=document.querySelector('#construction-fact');if(factForm)factForm.onsubmit=event=>{event.preventDefault();const form=event.currentTarget;request(`/construction/objects/${selected}/facts`,{quantity_id:val(form,'quantity_id'),quantity:val(form,'quantity')},detail)};
    const priceForm=document.querySelector('#construction-prices');
    if(priceForm){
      const checks=[...document.querySelectorAll('.construction-price-select')];
      const previewBox=document.querySelector('#construction-price-preview');
      const count=document.querySelector('#construction-price-count');
      const all=document.querySelector('#construction-price-all');
      let prepared=null;
      const selectedIds=()=>checks.filter(input=>input.checked).map(input=>input.value);
      const resetPreview=()=>{prepared=null;previewBox.replaceChildren();const size=selectedIds().length;count.textContent=size?`${size} из ${checks.length} позиций`:'Выберите позиции';all.textContent=size===Math.min(checks.length,50)?'Снять выбор':checks.length>50?'Выбрать первые 50':'Выбрать все'};
      checks.forEach(input=>input.onchange=()=>{if(selectedIds().length>50){input.checked=false;notify('За один раз можно изменить до 50 позиций')}resetPreview()});
      priceForm.elements.percent.oninput=resetPreview;
      all.onclick=()=>{const next=selectedIds().length!==Math.min(checks.length,50);checks.forEach((input,index)=>input.checked=next && index<50);resetPreview()};
      priceForm.onsubmit=async event=>{
        event.preventDefault();
        const ids=selectedIds();
        if(!ids.length){notify('Выберите хотя бы одну позицию');return}
        if(ids.length>50){notify('За один раз можно изменить до 50 позиций');return}
        const button=priceForm.querySelector('[type="submit"]');button.disabled=true;
        try{
          const percent=val(priceForm,'percent');
          prepared={ids,percent,...await send(`/construction/objects/${selected}/prices/preview`,{ids,percent})};
          if(ids.join('|')!==selectedIds().join('|') || percent!==val(priceForm,'percent')){resetPreview();return}
          previewBox.innerHTML=`<div class="construction-price-diff"><div class="construction-price-diff-head"><strong>Перед применением</strong><span>${money(prepared.old_total)} → ${money(prepared.new_total)}</span></div>${prepared.changes.map(item=>`<div class="construction-price-diff-row"><span>${esc(item.title)}</span><span>${money(item.old_unit_price)} → <b>${money(item.new_unit_price)}</b></span></div>`).join('')}<p class="construction-hint">Ранее отправленная смета не изменится. После применения создайте новую смету и передайте её клиенту.</p><button type="button" id="construction-price-apply" class="btn primary">Применить к ${prepared.changes.length} позициям</button></div>`;
          document.querySelector('#construction-price-apply').onclick=async event=>{
            const applyButton=event.currentTarget;applyButton.disabled=true;
            try{await send(`/construction/objects/${selected}/prices/apply`,{ids:prepared.ids,percent:prepared.percent,expected_hash:prepared.expected_hash});notify('Расценки обновлены');await detail()}
            catch(error){notify(error.message);resetPreview();}
          };
        }catch(error){notify(error.message);resetPreview()}
        finally{button.disabled=false}
      };
      const undo=document.querySelector('#construction-price-undo');
      if(undo)undo.onclick=async()=>{
        undo.disabled=true;
        try{await send(`/construction/objects/${selected}/prices/batches/${encodeURIComponent(data.latest_price_batch.id)}`,{});notify('Расценки восстановлены');await detail()}
        catch(error){notify(error.message);undo.disabled=false}
      };
    }
    const defectForm=document.querySelector('#construction-defect');defectForm.onsubmit=event=>{event.preventDefault();const form=event.currentTarget;request(`/construction/objects/${selected}/defects`,{zone_id:val(form,'zone_id'),photo_file_id:val(form,'photo_file_id'),severity:val(form,'severity'),description:val(form,'description'),measurement_note:val(form,'measurement_note'),suggested_work:val(form,'suggested_work')},detail)};
    document.querySelectorAll('[data-defect-status]').forEach(input=>input.onchange=event=>request(`/construction/objects/${selected}/defects/${input.dataset.defectStatus}`,{status:event.target.value},detail,'PATCH'));
    const logForm=document.querySelector('#construction-log');
    logForm.onsubmit=async event=>{event.preventDefault();const form=event.currentTarget;
      const photos=[...form.querySelectorAll('input[name="log_photo"]:checked')].map(input=>input.value);
      if(photos.length>4){notify('Выберите не больше четырёх фото');return}
      const payload={work_date:val(form,'work_date'),zone_id:val(form,'zone_id'),quantity_id:val(form,'quantity_id'),work_description:val(form,'work_description'),workers:val(form,'workers'),worker_count:val(form,'worker_count')||0,completed_quantity:val(form,'completed_quantity')||0,unit:val(form,'unit'),comment:val(form,'comment')};
      const editing=logs.find(item=>item.id===form.dataset.edit);
      try{if(editing){const path=`/construction/objects/${selected}/logs/${editing.id}`;await api(path,{method:'PATCH',body:JSON.stringify(payload)});
          for(const id of editing.photo_file_ids||[])if(!photos.includes(id))await api(path+'/photos/'+encodeURIComponent(id),{method:'DELETE'});
          for(const id of photos)if(!(editing.photo_file_ids||[]).includes(id))await api(path+'/photos',{method:'POST',body:JSON.stringify({file_id:id})});
        }else await api(`/construction/objects/${selected}/logs`,{method:'POST',body:JSON.stringify({...payload,photo_file_ids:photos})});
        await detail();
      }catch(error){notify(error.message)}
    };
    document.querySelectorAll('[data-log-edit]').forEach(button=>button.onclick=()=>{const item=logs.find(row=>row.id===button.dataset.logEdit);logForm.dataset.edit=item.id;
      for(const key of ['work_date','zone_id','quantity_id','work_description','workers','worker_count','completed_quantity','unit','comment'])logForm.elements[key].value=item[key]??'';
      logForm.querySelectorAll('input[name="log_photo"]').forEach(input=>input.checked=(item.photo_file_ids||[]).includes(input.value));
      logForm.querySelector('.btn').textContent='Сохранить запись';logForm.querySelector('#construction-log-cancel').hidden=false;logForm.scrollIntoView({behavior:'smooth',block:'center'});
    });
    document.querySelector('#construction-log-cancel').onclick=()=>{delete logForm.dataset.edit;logForm.reset();logForm.querySelector('.btn').textContent='Записать день';logForm.querySelector('#construction-log-cancel').hidden=true};
    document.querySelectorAll('[data-log-delete]').forEach(button=>button.onclick=async()=>{if(!confirm('Удалить запись журнала и связанный фактический объём?'))return;
      try{await api(`/construction/objects/${selected}/logs/${button.dataset.logDelete}`,{method:'DELETE'});await detail()}catch(error){notify(error.message)}
    });
    const supplierForm=document.querySelector('#construction-supplier');supplierForm.onsubmit=event=>{event.preventDefault();request('/construction/suppliers',{name:val(supplierForm,'name'),phone:val(supplierForm,'phone'),email:val(supplierForm,'email')},detail)};
    const purchaseForm=document.querySelector('#construction-purchase');
    purchaseForm.insertAdjacentHTML('beforeend','<button class="construction-edit" id="construction-receipt-ocr" type="button">Заполнить по фото чека</button><p class="construction-hint" id="construction-ocr-note">Проверьте сумму и дату перед сохранением. 3 распознавания в месяц бесплатно.</p>');
    document.querySelector('#construction-receipt-ocr').onclick=async event=>{
      const fileId=val(purchaseForm,'receipt_file_id');
      if(!fileId){notify('Выберите прикреплённое фото чека');return}
      const button=event.currentTarget;button.disabled=true;
      try{
        const result=await api(`/construction/objects/${selected}/receipt-ocr`,{method:'POST',body:JSON.stringify({file_id:fileId})});
        const draft=result.draft;
        if(draft.date)purchaseForm.elements.purchased_on.value=draft.date;
        const quantity=number(val(purchaseForm,'quantity'));
        if(draft.amount_kopecks&&quantity>0)purchaseForm.elements.unit_price.value=(draft.amount_kopecks/100/quantity).toFixed(2);
        if(draft.merchant)purchaseForm.elements.notes.value=draft.merchant;
        document.querySelector('#construction-ocr-note').textContent='Распознано: '+(draft.merchant||'магазин не найден')+' · '+(draft.amount_kopecks?money(draft.amount_kopecks):'сумма не найдена')+'. Проверьте все поля и нажмите «Записать закупку».';
      }catch(error){notify(error.message)}finally{button.disabled=false}
    };
    purchaseForm.onsubmit=event=>{event.preventDefault();const form=event.currentTarget;
      const payload={material_id:val(form,'material_id'),supplier_id:val(form,'supplier_id'),purchased_on:val(form,'purchased_on'),quantity:val(form,'quantity'),unit_price_kopecks:Math.round(number(val(form,'unit_price'))*100),status:val(form,'status'),receipt_file_id:val(form,'receipt_file_id'),notes:val(form,'notes')};
      request(`/construction/objects/${selected}/purchases${form.dataset.edit?'/'+form.dataset.edit:''}`,payload,detail,form.dataset.edit?'PATCH':'POST');
    };
    document.querySelectorAll('[data-purchase-edit]').forEach(button=>button.onclick=()=>{const item=purchases.find(row=>row.id===button.dataset.purchaseEdit);purchaseForm.dataset.edit=item.id;
      for(const key of ['material_id','supplier_id','purchased_on','quantity','status','receipt_file_id','notes'])purchaseForm.elements[key].value=item[key]??'';
      purchaseForm.elements.unit_price.value=item.unit_price_kopecks/100;purchaseForm.querySelector('.btn').textContent='Сохранить закупку';purchaseForm.querySelector('#construction-purchase-cancel').hidden=false;purchaseForm.scrollIntoView({behavior:'smooth',block:'center'});
    });
    document.querySelector('#construction-purchase-cancel').onclick=()=>{delete purchaseForm.dataset.edit;purchaseForm.reset();purchaseForm.querySelector('.btn').textContent='Записать закупку';purchaseForm.querySelector('#construction-purchase-cancel').hidden=true};
    document.querySelectorAll('[data-purchase-delete]').forEach(button=>button.onclick=async()=>{if(!confirm('Удалить запись о закупке?'))return;try{await api(`/construction/objects/${selected}/purchases/${button.dataset.purchaseDelete}`,{method:'DELETE'});await detail()}catch(error){notify(error.message)}});
    const changeForm=document.querySelector('#construction-change'),changeLines=document.querySelector('#construction-change-lines');
    document.querySelector('#construction-change-add').onclick=()=>{if(changeLines.children.length>=20){notify('Не больше 20 позиций в одной форме');return}changeLines.insertAdjacentHTML('beforeend',changeLine())};
    changeLines.onclick=event=>{if(event.target.closest('[data-change-remove]')&&changeLines.children.length>1)event.target.closest('.construction-change-line').remove()};
    changeForm.onsubmit=event=>{event.preventDefault();const items=[...changeLines.querySelectorAll('.construction-change-line')].map(line=>({name:val(line,'name'),quantity:val(line,'quantity'),unit:val(line,'unit'),unit_price:Math.round(number(val(line,'price'))*100)}));
      request(`/construction/objects/${selected}/changes${changeForm.dataset.edit?'/'+changeForm.dataset.edit:''}`,{title:val(changeForm,'title'),description:val(changeForm,'description'),deadline_days:val(changeForm,'deadline_days')||0,items},detail,changeForm.dataset.edit?'PATCH':'POST');
    };
    document.querySelectorAll('[data-change-edit]').forEach(button=>button.onclick=()=>{const item=changes.find(row=>row.id===button.dataset.changeEdit);changeForm.dataset.edit=item.id;
      for(const key of ['title','description','deadline_days'])changeForm.elements[key].value=item[key]??'';
      changeLines.innerHTML=item.items.map(changeLine).join('');changeForm.querySelector('button[type="submit"]').textContent='Сохранить версию';document.querySelector('#construction-change-cancel').hidden=false;changeForm.scrollIntoView({behavior:'smooth',block:'center'});
    });
    document.querySelector('#construction-change-cancel').onclick=()=>{delete changeForm.dataset.edit;changeForm.reset();changeLines.innerHTML=changeLine();changeForm.querySelector('button[type="submit"]').textContent='Сохранить черновик';document.querySelector('#construction-change-cancel').hidden=true};
    document.querySelectorAll('[data-change-send]').forEach(button=>button.onclick=()=>{if(confirm('Отправить эту версию на отдельное согласование клиенту?'))request(`/construction/objects/${selected}/changes/${button.dataset.changeSend}/send`,{},detail)});
    document.querySelectorAll('[data-change-delete]').forEach(button=>button.onclick=async()=>{if(!confirm('Удалить черновик допработ?'))return;try{await api(`/construction/objects/${selected}/changes/${button.dataset.changeDelete}`,{method:'DELETE'});await detail()}catch(error){notify(error.message)}});
    document.querySelectorAll('[data-change-revoke]').forEach(button=>button.onclick=()=>{if(confirm('Отозвать ссылку? Клиент больше не сможет согласовать эту версию.'))request(`/construction/objects/${selected}/changes/${button.dataset.changeRevoke}/revoke`,{},detail)});
    document.querySelectorAll('[data-change-revise]').forEach(button=>button.onclick=()=>request(`/construction/objects/${selected}/changes/${button.dataset.changeRevise}/revise`,{},detail));
    document.querySelectorAll('[data-change-link]').forEach(button=>button.onclick=async()=>{const item=changes.find(row=>row.id===button.dataset.changeLink);const link=location.origin+'/change.html?token='+encodeURIComponent(item.public_token);
      try{await navigator.clipboard.writeText(link);notify('Ссылка скопирована')}catch(error){const input=document.createElement('input');input.value=link;document.body.appendChild(input);input.select();document.execCommand('copy');input.remove();notify('Ссылка скопирована')}
    });
    document.querySelector('#construction-export').onclick=downloadSheet;
    document.querySelector('#construction-import').onchange=importSheet;
    document.querySelector('#construction-quote')?.addEventListener('click',()=>request(`/construction/objects/${selected}/quote`,{},detail));
    document.querySelector('#construction-quote-open')?.addEventListener('click',()=>{location.hash='quotes';tab='quotes';window.render()});
    document.querySelector('#construction-act').onclick=downloadFactAct;
    document.querySelector('#construction-report').onclick=downloadReport;
    document.querySelector('#construction-project-open')?.addEventListener('click',()=>{location.hash='projects';tab='projects';window.render()});
    document.querySelector('#construction-file').onchange=upload;
    loadFiles();
  }
  async function loadFiles(){
    try{const files=(await api('/files?construction_id='+encodeURIComponent(selected))).items;
      const count=document.querySelector('#construction-file-count'),list=document.querySelector('#construction-files');if(!count||!list)return;
      count.textContent=files.length;list.innerHTML=files.map(file=>`<div class="construction-row"><strong>${esc(file.name)}</strong><span>${Math.ceil(file.size/1024)} КБ</span><button class="btn small" data-file="${esc(file.id)}">Открыть</button></div>`).join('')||'<p class="construction-empty">Файлов пока нет.</p>';
      const photoSelect=document.querySelector('#construction-defect-photo');if(photoSelect)photoSelect.innerHTML='<option value="">Без фото</option>'+files.filter(file=>file.mime.startsWith('image/')).map(file=>`<option value="${esc(file.id)}">${esc(file.name)}</option>`).join('');
      const receiptSelect=document.querySelector('#construction-purchase-receipt');if(receiptSelect)receiptSelect.innerHTML='<option value="">Без файла</option>'+files.filter(file=>file.mime.startsWith('image/')||file.mime==='application/pdf').map(file=>`<option value="${esc(file.id)}">${esc(file.name)}</option>`).join('');
      const logPhotos=document.querySelector('#construction-log-photo-options');if(logPhotos)logPhotos.innerHTML=files.filter(file=>file.mime.startsWith('image/')).map(file=>`<label><input type="checkbox" name="log_photo" value="${esc(file.id)}"><span>${esc(file.name)}</span></label>`).join('')||'<small>Сначала прикрепите фото к объекту ниже.</small>';
      list.querySelectorAll('[data-file]').forEach(button=>button.onclick=()=>{const file=files.find(item=>item.id===button.dataset.file);window.SmetraFilePreview?.open(file,sessionStorage.getItem('workspace_id'))});
      document.querySelectorAll('[data-defect-photo]').forEach(button=>button.onclick=()=>{const file=files.find(item=>item.id===button.dataset.defectPhoto);if(file)window.SmetraFilePreview?.open(file,sessionStorage.getItem('workspace_id'))});
      document.querySelectorAll('[data-log-photo]').forEach(button=>button.onclick=()=>{const file=files.find(item=>item.id===button.dataset.logPhoto);if(file)window.SmetraFilePreview?.open(file,sessionStorage.getItem('workspace_id'))});
      document.querySelectorAll('[data-purchase-receipt]').forEach(button=>button.onclick=()=>{const file=files.find(item=>item.id===button.dataset.purchaseReceipt);if(file)window.SmetraFilePreview?.open(file,sessionStorage.getItem('workspace_id'))});
    }catch(error){notify(error.message)}
  }
  async function upload(event){
    const file=event.target.files[0];if(!file)return;if(file.size>5000000){notify('Максимум 5 МБ');return}
    try{const bytes=new Uint8Array(await file.arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=32768)text+=String.fromCharCode(...bytes.subarray(i,i+32768));await send('/files',{construction_id:selected,name:file.name,content:btoa(text)});await loadFiles();notify('Файл прикреплён')}
    catch(error){notify(error.message)}finally{event.target.value=''}
  }
  async function importSheet(event){
    const file=event.target.files[0];if(!file)return;if(file.size>1500000){notify('Ведомость XLSX должна быть меньше 1,5 МБ');return}
    try{const bytes=new Uint8Array(await file.arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=32768)text+=String.fromCharCode(...bytes.subarray(i,i+32768));const result=await send(`/construction/objects/${selected}/import`,{content:btoa(text)});notify('Импортировано позиций: '+result.imported);await detail()}
    catch(error){notify(error.message)}finally{event.target.value=''}
  }
  async function downloadSheet(){
    try{const headers={};const workspace=sessionStorage.getItem('workspace_id');if(workspace)headers['X-Workspace-Id']=workspace;
      const response=await fetch('/api/construction/objects/'+encodeURIComponent(selected)+'/xlsx',{credentials:'same-origin',headers});if(!response.ok)throw Error((await response.json()).error||'Ошибка экспорта');const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='smetra-vedomost.xlsx';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}catch(error){notify(error.message)}
  }
  async function downloadFactAct(){
    const button=document.querySelector('#construction-act');button.disabled=true;
    try{const result=await api(`/construction/objects/${selected}/act`,{method:'POST',body:'{}'});
      const headers={};const workspace=sessionStorage.getItem('workspace_id');if(workspace)headers['X-Workspace-Id']=workspace;
      const response=await fetch('/api/documents/'+encodeURIComponent(result.document.id)+'/pdf',{credentials:'same-origin',headers});
      if(!response.ok)throw Error((await response.json()).error||'Не удалось скачать акт');
      const url=URL.createObjectURL(await response.blob()),anchor=document.createElement('a');anchor.href=url;anchor.download='smetra-akt-'+result.document.number+'.pdf';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),5000);
      notify('Черновик акта сохранён в документах');
    }catch(error){notify(error.message)}finally{button.disabled=false}
  }
  async function downloadReport(){
    const button=document.querySelector('#construction-report');button.disabled=true;
    try{const headers={};const workspace=sessionStorage.getItem('workspace_id');if(workspace)headers['X-Workspace-Id']=workspace;
      const response=await fetch('/api/construction/objects/'+encodeURIComponent(selected)+'/report.pdf',{credentials:'same-origin',headers});
      if(!response.ok)throw Error((await response.json()).error||'Не удалось сформировать отчёт');
      const url=URL.createObjectURL(await response.blob()),anchor=document.createElement('a');anchor.href=url;anchor.download='smetra-report.pdf';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),5000);
    }catch(error){notify(error.message)}finally{button.disabled=false}
  }
  window.SmetraConstruction = () => selected ? detail() : list();
})();
