/* Workspace Markdown notes use the same safe renderer as assistant replies. */
window.SmetraFileEditor = (() => {
  const html = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const encode = value => {const bytes=new TextEncoder().encode(value);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)};
  async function open(file=null) {
    let content='';let places=[];
    try {
      if(file){const headers={};const workspace=sessionStorage.getItem('workspace_id');if(workspace)headers['X-Workspace-Id']=workspace;const response=await fetch('/api/files/'+encodeURIComponent(file.id),{credentials:'same-origin',headers});if(!response.ok)throw Error('Не удалось открыть документ');content=await response.text()}
      else {const [projects,objects]=await Promise.all([api('/projects'),api('/construction/objects')]);places=[...projects.items.map(item=>['project_id',item.id,'Заказ · '+item.name]),...objects.items.map(item=>['construction_id',item.id,'Объект · '+item.name])]}
    }catch(error){notify(error.message);return}
    view(`<div class="file-editor-top"><button type="button" id="file-editor-back">← Файлы</button><span>СМЕТРА / ДОКУМЕНТ</span></div><div class="topline"><div><h1>${file?'Редактировать заметку':'Новая заметка'}</h1><p class="muted">Markdown-документ внутри вашего рабочего пространства.</p></div></div>
      <form id="file-editor-form" class="file-editor-layout"><section class="file-editor-input"><div class="file-editor-fields"><label><span>Название</span><input name="name" maxlength="176" required value="${html(file?file.name.replace(/\.md$/i,''):'')}" ${file?'readonly':''} placeholder="Например, осмотр кухни"></label>${file?'':`<label><span>Сохранить в</span><select name="target" required>${places.length?places.map(item=>`<option value="${html(item[0]+':'+item[1])}">${html(item[2])}</option>`).join(''):'<option value="">Сначала создайте объект или заказ</option>'}</select></label>`}</div><label class="file-editor-text-label" for="file-editor-text">Текст</label><textarea id="file-editor-text" name="content" maxlength="500000" spellcheck="true" placeholder="# Осмотр\n\nЧто измерили и что осталось проверить…"></textarea><div class="file-editor-actions"><button class="btn primary" ${!file&&!places.length?'disabled':''}>Сохранить документ</button>${file?'<button class="btn ghost" type="button" id="file-editor-improve">Улучшить выделенное</button>':''}<span id="file-editor-status" role="status"></span></div></section><section class="file-editor-preview"><span class="overline">ПРЕДПРОСМОТР</span><div id="file-editor-render" class="assistant-markdown"></div>${file?'<div class="file-editor-history"><div class="file-editor-history-head"><span class="overline">ИСТОРИЯ ИЗМЕНЕНИЙ</span><button type="button" id="file-editor-history-refresh">Обновить</button></div><div id="file-editor-history-list" role="status">Загружаем…</div><div id="file-editor-history-preview" class="assistant-markdown" hidden></div><button type="button" class="btn ghost" id="file-editor-restore" hidden>Восстановить эту версию</button></div>':''}</section></form>`);
    const form=document.querySelector('#file-editor-form'),input=form.elements.content,preview=document.querySelector('#file-editor-render');input.value=content;
    const paint=()=>{preview.innerHTML=typeof window.assistantMarkdown==='function'?window.assistantMarkdown(input.value):html(input.value).replace(/\n/g,'<br>');if(!preview.innerHTML)preview.textContent='Здесь появится документ.'};paint();input.oninput=paint;
    if(file){
      document.querySelector('#file-editor-improve').onclick=()=>{const selected=input.value.slice(input.selectionStart,input.selectionEnd);const status=document.querySelector('#file-editor-status');if(!selected.trim()){status.textContent='Выделите текст, который нужно улучшить.';input.focus();return}if(selected.length>1200){status.textContent='Выделите не больше 1200 символов.';return}if(input.value!==content){status.textContent='Сначала сохраните документ, чтобы ассистент работал с актуальной версией.';return}const workspace=window.Workspace?.currentWorkspaceId?.()||sessionStorage.getItem('workspace_id')||'';window.SmetraAssistantContext?.({entity:'files',id:file.id,label:file.name,workspace_id:workspace});sessionStorage.setItem('smetra.assistant.prefill',JSON.stringify({workspace_id:workspace,file_id:file.id,text:'Улучши формулировку выделенного фрагмента в Markdown-документе. Старый текст дословно: '+JSON.stringify(selected)+'. Предложи точечную замену через replace_markdown_text. Не меняй другие части документа и не применяй правку без моего подтверждения.'}));location.hash='assistant';tab='assistant';window.render()};
      const list=document.querySelector('#file-editor-history-list'),oldPreview=document.querySelector('#file-editor-history-preview'),restore=document.querySelector('#file-editor-restore');
      let selected=null;
      const decode=value=>new TextDecoder().decode(Uint8Array.from(atob(value),char=>char.charCodeAt(0)));
      const loadHistory=async()=>{list.textContent='Загружаем…';selected=null;oldPreview.hidden=true;restore.hidden=true;try{const result=await api('/files/'+encodeURIComponent(file.id)+'/versions');list.replaceChildren();if(!result.items.length){list.textContent='История появится после первого изменения.';return}for(const item of result.items){const button=document.createElement('button');button.type='button';button.className='file-editor-version';button.textContent='Версия '+item.revision+' · '+new Date(item.created_at*1000).toLocaleString('ru-RU');button.onclick=async()=>{try{const version=await api('/files/'+encodeURIComponent(file.id)+'/versions/'+encodeURIComponent(item.id));selected={id:item.id,text:decode(version.content)};oldPreview.innerHTML=typeof window.assistantMarkdown==='function'?window.assistantMarkdown(selected.text):html(selected.text).replace(/\n/g,'<br>');oldPreview.hidden=false;restore.hidden=false}catch(error){notify(error.message)}};list.append(button)}}catch(error){list.textContent=error.message}};
      document.querySelector('#file-editor-history-refresh').onclick=loadHistory;
      restore.onclick=async()=>{if(!selected)return;if(input.value!==content&&!confirm('Есть несохранённые изменения. Восстановить выбранную версию?'))return;restore.disabled=true;try{const result=await api('/files/'+encodeURIComponent(file.id)+'/versions/'+encodeURIComponent(selected.id)+'/restore',{method:'POST',body:JSON.stringify({sha256:file.sha256})});file.sha256=result.file.sha256;content=selected.text;input.value=content;paint();notify('Версия восстановлена');await loadHistory()}catch(error){notify(error.message)}finally{restore.disabled=false}};
      loadHistory();
    }
    document.querySelector('#file-editor-back').onclick=()=>{location.hash='files';tab='files';window.render()};
    form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button[type="submit"],button.btn.primary');button.disabled=true;const status=document.querySelector('#file-editor-status');status.textContent='Сохраняем…';try{const text=input.value;if(!text.trim())throw Error('Добавьте текст документа');const body={content:encode(text)};let path='/files',method='POST';if(file){body.sha256=file.sha256;path+='/'+encodeURIComponent(file.id);method='PATCH'}else{const target=form.elements.target.value.split(':');body[target[0]]=target[1];body.name=form.elements.name.value.trim().replace(/\.md$/i,'')+'.md'}await api(path,{method,body:JSON.stringify(body)});notify('Документ сохранён');location.hash='files';tab='files';window.render()}catch(error){status.textContent=error.message;button.disabled=false}};
  }
  return {open};
})();
