/* Activation and paid value. Pricing and entitlements always come from the API. */
(() => {
 const e=escapeHtml;
 const track=(name,source)=>api('/billing/events',{method:'POST',body:JSON.stringify({name,source})}).catch(()=>{});
 const starterNames={repair:'Ремонт',building:'Строительство',installation:'Монтаж',design:'Дизайн',equipment:'Ремонт техники',services:'Услуги',other:'Другое'};
 const starters={repair:['Подготовительные работы','Отделочные работы','Материалы'],building:['Подготовка площадки','Основные работы','Материалы'],installation:['Подготовка к монтажу','Монтаж','Проверка и запуск'],design:['Концепция','Разработка проекта','Подготовка материалов'],equipment:['Диагностика','Ремонт','Запасные части'],services:['Подготовка','Основная работа','Передача результата'],other:['Работа']};
 function start(goal='estimate'){
  const owner=user;
  view(`<section class="activation-page"><span class="overline">Первая полезная смета</span><h1>Что нужно рассчитать?</h1><p class="muted">Выберите основу. Останется указать клиента, объёмы и ваши цены.</p><div class="activation-starters">${Object.keys(starters).map(key=>`<button class="btn" type="button" data-starter="${key}"><img class="icon" src="/assets/icons/file-text.svg" alt="">${starterNames[key]}<span aria-hidden="true">↗</span></button>`).join('')}</div><button class="btn" id="activation-blank" type="button">Начать с пустой сметы</button><button class="btn" id="activation-back" type="button">Назад</button><p class="note">Заготовки не содержат рыночных цен. Итог рассчитаете по своим условиям.</p></section>`);
  document.querySelector('#activation-back').onclick=()=>render();
  document.querySelector('#activation-blank').onclick=()=>Workspace.editor();
  document.querySelectorAll('[data-starter]').forEach(button=>button.onclick=()=>{if(user!==owner)return;const key=button.dataset.starter;Workspace.editor({title:(goal==='proposal'?'Предложение · ':goal==='order'?'Заказ · ':'')+starterNames[key],description:'',items:starters[key].map(name=>({name,quantity:'1',unit:'усл.',unit_price:0,cost_price:0,included:true,optional:false}))})});
 }
 function onboarding(host){
  if(!host||user.quote_count>0||host.querySelector('.activation-intro'))return;
  host.insertAdjacentHTML('afterbegin',`<section class="activation-intro"><span class="overline">Начните с результата</span><h2>Что хотите сделать?</h2><div class="row wrap"><button class="btn primary" data-activation="estimate">Создать смету</button><button class="btn" data-activation="order">Рассчитать заказ</button><button class="btn" data-activation="proposal">Подготовить предложение</button></div><p class="note">Первая смета бесплатно. Ссылку и PDF можно отправить клиенту.</p></section>`);
  host.querySelectorAll('[data-activation]').forEach(button=>button.onclick=()=>start(button.dataset.activation));
 }
 async function paywall(source='other'){
  if(!user||user.plan==='pro')return;
  const key='smetra.paywall.'+user.id+'.'+source;
  if(Date.now()-Number(sessionStorage.getItem(key)||0)<1800000)return;
  sessionStorage.setItem(key,String(Date.now()));
  // Keep the user's draft and working page intact. Never interrupt with a modal.
  const old=document.querySelector('.contextual-upgrade');old?.remove();
  const notice=document.createElement('section');notice.className='contextual-upgrade';notice.setAttribute('role','status');
  notice.innerHTML='<div><strong>Продолжите работу в Про</strong><p>Больше смет и помощи ассистента. Ваши данные и черновик сохранятся.</p></div><button class="btn primary" type="button">Посмотреть Про</button><button class="icon-button" type="button" aria-label="Закрыть предложение">×</button>';
  document.querySelector('#content')?.prepend(notice);
  notice.querySelector('.icon-button').onclick=()=>notice.remove();notice.querySelector('.primary').onclick=()=>{document.querySelector('#local-draft')?.click();sessionStorage.setItem('smetra.checkout.return.'+user.id,tab);sessionStorage.setItem('smetra.paywall.source',source);track('upgrade_clicked',source);tab='billing';location.hash='billing';render()};track('paywall_viewed',source);
 }
 async function billing(active){
  const owner=user,[b,space]=await Promise.all([api('/billing'),api('/workspace')]);if(!active())return;
  const pricing=b.pricing;
  if(!pricing)throw Error('Не удалось получить условия тарифа. Повторите загрузку.');
  const source=sessionStorage.getItem('smetra.paywall.source')||'pricing_page';
  const pro=owner.plan==='pro'&&owner.entitlement_until>Date.now()/1000;
  const ready=b.email_verified&&['test','live'].includes(b.checkout_mode);
  const ownSpace=space.workspace?.owner_id===owner.id;
  const note=b.checkout_mode==='off'?'Оплата временно недоступна. Ваш текущий доступ сохраняется.':!b.email_verified?'Для оплаты нужна подтверждённая почта аккаунта.':b.checkout_mode==='test'?'Тестовый режим: деньги не списываются.':'Защищённая оплата через ЮKassa. Без автоматических списаний.';
  const pending=b.payments.find(p=>p.status==='pending');
  const recent=b.payments[0];
  const paymentNames={pending:'Ожидает оплаты',succeeded:'Оплачено',canceled:'Отменено',refunded:'Возврат'};
  view(`<section class="revenue-billing"><header><span class="overline">Сметра Про</span><h1>${pro?'Продолжайте в своём ритме.':'Меньше рутины.<br>Больше готовых предложений.'}</h1><p class="muted">Готовьте сметы, отправляйте условия клиентам и ведите заказы в одном месте.</p><p class="note">${pro?'Про активен до '+date(owner.entitlement_until):'Сейчас тариф Старт · первые '+pricing.limits.free_quotes+' смет бесплатно'} · сайт и приложение</p></header>
   <section class="payment-recovery" ${pending||recent?.status==='canceled'||new URLSearchParams(location.search).has('payment')?'':'hidden'}><strong>${pending?'Оплата не завершена':pro?'Про активирован':'Оплата не завершена'}</strong><p class="muted">${pending?'Вы можете продолжить оплату или проверить её статус.':pro?'Доступ уже действует на всех устройствах.':'Повторная попытка не изменит ваш текущий тариф.'}</p><div class="row wrap">${pending&&ready?'<button class="btn primary" id="checkout-resume" type="button">Продолжить оплату</button>':''}<button class="btn" id="payment-continue" type="button">Продолжить работу</button></div></section>
   <div class="billing-periods" role="group" aria-label="Срок доступа"><button class="btn" type="button" data-period="pro_month" aria-pressed="true">31 день</button><button class="btn" type="button" data-period="pro_year" aria-pressed="false">Год · 366 дней</button></div>
   ${pricing.launch_offer?`<p class="launch-offer">${e(pricing.launch_offer.label)} · до ${date(pricing.launch_offer.until)}</p>`:''}
   <div class="revenue-offer"><div><div class="open-price" id="offer-price"></div><p class="note" id="offer-saving"></p><button class="btn primary" data-plan="pro_month" id="upgrade-checkout" type="button" ${ready?'':'disabled'}>${pro?'Продлить Про':'Перейти на Про'}</button><p class="note">${e(note)}</p><p id="checkout-error" role="alert"></p></div><ul class="open-benefits"><li>Больше предложений клиентам — до ${pricing.limits.pro_quotes.toLocaleString('ru-RU')} смет</li><li>Ассистент помогает с расчётами — ${pricing.limits.pro_ai} сообщений в месяц</li><li>Сметы, предложения, акты и счета в PDF</li><li>Условия, версии, заказы и поступления рядом</li><li>Один профиль на сайте и в приложении</li></ul></div>
   <section class="billing-history"><div class="section-top"><h2>Оплаты</h2><button class="btn small" id="sync" type="button">Проверить оплату</button></div>${b.payments.length?b.payments.map(p=>`<div class="record-line"><div><strong>Про · ${p.plan==='pro_year'?'год':'31 день'}</strong><small>${date(p.created_at)} · ${e(paymentNames[p.status]||p.status)}</small></div><b>${rub(p.amount_kopecks)}</b></div>`).join(''):'<p class="muted">Здесь появятся ваши оплаты подписки.</p>'}</section>
   <section class="billing-referral"><h2>Пригласите коллегу</h2><p class="muted">Получите 3 дополнительных сообщения ассистенту, когда коллега создаст первую смету. До 30 бонусных сообщений в месяц.</p><button class="btn" type="button" id="referral-copy">Скопировать приглашение</button><span id="referral-status" role="status"></span></section>
   <p class="note billing-legal">Оплату принимает самозанятый МУРАВЬЕВ КОНСТАНТИН АЛЕКСЕЕВИЧ · ИНН 713304603876. <a href="/terms">Условия оплаты и возврата</a> · <a href="/contacts">Контакты</a></p></section>`);
  let plan='pro_month';const checkout=document.querySelector('#upgrade-checkout');
  const paint=()=>{const amount=pricing.plans[plan].amount_kopecks;checkout.dataset.plan=plan;document.querySelector('#offer-price').textContent=rub(amount);document.querySelector('#offer-saving').textContent=plan==='pro_year'?rub(Math.round(amount/12))+' в месяц · экономия '+rub(pricing.annual_saving_kopecks)+' за 12 периодов':'Один платёж за 31 день';document.querySelectorAll('[data-period]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.period===plan)))};paint();
  document.querySelectorAll('[data-period]').forEach(button=>button.onclick=()=>{plan=button.dataset.period;paint()});
  const retryCancelled=recent&&['canceled','refunded'].includes(recent.status);if(retryCancelled)for(const value of ['pro_month','pro_year'])sessionStorage.removeItem('smetra.checkout.'+owner.id+'.'+value);
  checkout.onclick=async()=>{if(checkout.disabled)return;checkout.disabled=true;const selected=plan,keyName='smetra.checkout.'+owner.id+'.'+selected;let key=sessionStorage.getItem(keyName);if(!key){key=crypto.randomUUID();sessionStorage.setItem(keyName,key)}track('upgrade_clicked',source);if(!sessionStorage.getItem('smetra.checkout.return.'+owner.id))sessionStorage.setItem('smetra.checkout.return.'+owner.id,'dashboard');try{const result=await api('/billing/checkout',{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify({plan:selected,source})});if(!active())return;if(result.status==='canceled'){sessionStorage.removeItem(keyName);throw Error('Предыдущая оплата отменена. Нажмите ещё раз для новой попытки.')}if(result.status==='succeeded'){await sync();return}location.href=result.url}catch(error){if(active()){if(error.status===409)sessionStorage.removeItem(keyName);document.querySelector('#checkout-error').textContent=error.message}}finally{if(checkout.isConnected)checkout.disabled=false}};
  async function sync(){const button=document.querySelector('#sync');if(!button||button.disabled)return;button.disabled=true;try{const result=await api('/billing/sync',{method:'POST'});if(user!==owner)return;user=result.user;if(user.plan==='pro'){for(const value of ['pro_month','pro_year'])sessionStorage.removeItem('smetra.checkout.'+owner.id+'.'+value)}if(tab==='billing')await render();notify(result.payments?.some(p=>p.status==='pending')?'Оплата пока не завершена. Текущий доступ сохранён.':user.plan==='pro'?'Про активен. Можно продолжать работу.':'Оплата пока не подтверждена. Доступ остаётся на тарифе Старт.')}catch(error){if(user===owner)notify(error.message)}finally{if(button.isConnected)button.disabled=false}}
  document.querySelector('#sync').onclick=sync;
  if(ownSpace){const branding=document.createElement('button');branding.className='btn';branding.type='button';const hidden=space.workspace.settings?.hide_branding===true;branding.textContent=hidden?'Показывать отметку Сметры':'Убрать отметку Сметры · Про';document.querySelector('.billing-referral').before(branding);branding.onclick=async()=>{if(branding.disabled)return;if(!pro){paywall('pdf_export');return}branding.disabled=true;try{await api('/workspace',{method:'PATCH',body:JSON.stringify({settings:{hide_branding:!hidden}})});if(active())await render();notify('Оформление новых PDF и клиентских страниц обновлено')}catch(error){if(active())notify(error.message)}finally{if(branding.isConnected)branding.disabled=false}};}
  const resume=document.querySelector('#checkout-resume');if(resume)resume.onclick=()=>{if(pending.confirmation_url?.startsWith('https://'))location.href=pending.confirmation_url};
  document.querySelector('#payment-continue').onclick=()=>{const previous=sessionStorage.getItem('smetra.checkout.return.'+owner.id)||'dashboard';tab=['quotes','projects','assistant','documents','files','dashboard'].includes(previous)?previous:'dashboard';history.replaceState({},'','/app#'+tab);render()};
  document.querySelector('#referral-copy').onclick=async event=>{const button=event.currentTarget;if(button.disabled)return;button.disabled=true;try{const result=await api('/billing/referral');if(!active())return;await navigator.clipboard.writeText(location.origin+'/app?register=1&ref='+encodeURIComponent(result.code));document.querySelector('#referral-status').textContent='Приглашение скопировано'}catch(error){if(active())document.querySelector('#referral-status').textContent=error.message}finally{button.disabled=false}};
  track('paywall_viewed',source);
  if(pending&&new URLSearchParams(location.search).has('payment')){const pollKey='smetra.payment.poll.'+owner.id+'.'+pending.id,count=Number(sessionStorage.getItem(pollKey)||0);if(count<3){sessionStorage.setItem(pollKey,String(count+1));setTimeout(()=>{if(active()&&document.visibilityState==='visible')sync()},10000)}}
 }
 window.SmetraGrowth={billing,onboarding,start,paywall};
})();
