const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const watchdog=setTimeout(()=>{console.error('FAIL: office browser verification timed out');process.exit(1)},90000);
 const tabs=await(await fetch('http://127.0.0.1:'+(process.env.SMETRA_CDP_PORT||'9223')+'/json')).json();
 const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let sequence=0;const pending=new Map(),errors=[];
 ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id){const p=pending.get(message.id);pending.delete(message.id);message.error?p.reject(message.error):p.resolve(message.result)}else if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails.text)});
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const until=async expression=>{for(let i=0;i<120;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error(expression+'\n'+await evaluate('document.body.innerText'))};
 const screenshot=async name=>{const shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('data/'+name+'.png',Buffer.from(shot.data,'base64'))};
 await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await send('Page.navigate',{url:'http://localhost:8084/app'});await until("document.querySelector('#auth-form')?.onsubmit");await evaluate('sessionStorage.clear()');
 await evaluate("document.querySelector('#email').value='android-design@test.invalid';document.querySelector('#password').value='android design test only';document.querySelector('#auth-submit').click()");await until("document.querySelector('[data-work=quote-new]')");
 await evaluate("document.querySelector('[data-tab=files]').click()");await until("document.querySelector('[data-file-open]')");
 const files=await evaluate("api('/files').then(r=>r.items)");
 const open=async name=>{const file=files.find(f=>f.name===name);assert.ok(file);await evaluate(`document.querySelector('[data-file-open="${file.id}"]').click()`);await until("document.querySelector('.file-office-toolbar input')");return file};
 await open('brief.docx');assert.ok((await evaluate("document.querySelector('.file-office-content').textContent")).includes('Техническое задание'));
 assert.equal(await evaluate("document.querySelectorAll('.file-office-content img,.file-office-content script').length"),0);
 await evaluate("const search=document.querySelector('.file-office-toolbar input');search.value='Покраска';search.dispatchEvent(new Event('input'))");
 assert.equal(await evaluate("document.querySelector('.file-office-content').textContent.includes('Техническое задание')"),false);assert.ok(await evaluate("document.querySelector('.file-office-content mark')?.textContent==='Покраска'"));await screenshot('office-docx-mobile');
 await evaluate("document.querySelector('.file-preview-close').click()");await open('prices.xlsx');
 assert.ok((await evaluate("document.querySelector('.file-office-content').textContent")).includes('Формула (не рассчитана)'));
 await evaluate("document.querySelector('[aria-label=\"Сортировать столбец B\"]').click()");assert.equal(await evaluate("document.querySelector('.file-office-table tbody tr td:nth-child(3)').textContent"),'2000');
 const width=await evaluate("document.querySelector('.file-office-table colgroup').children[2].style.width");
 await evaluate("document.querySelector('[aria-label=\"Ширина столбца B\"]').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}))");assert.equal(await evaluate("parseInt(document.querySelector('.file-office-table colgroup').children[2].style.width)"),parseInt(width)+20);
 await evaluate("const search=document.querySelector('.file-office-toolbar input');search.value='Покраска';search.dispatchEvent(new Event('input'))");assert.equal(await evaluate("document.querySelectorAll('.file-office-table tbody tr').length"),1);
 await evaluate("const search=document.querySelector('.file-office-toolbar input');search.value='';search.dispatchEvent(new Event('input'));const select=document.querySelector('.file-office-toolbar select');select.value='1';select.dispatchEvent(new Event('change'))");assert.ok((await evaluate("document.querySelector('.file-office-content').textContent")).includes('Краска'));await screenshot('office-xlsx-mobile');
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 await evaluate("document.querySelector('.file-preview-close').click()");await open('prices.csv');assert.ok((await evaluate("document.querySelector('.file-office-content').textContent")).includes('15000'));
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});await screenshot('office-csv-desktop');assert.deepEqual(errors,[]);await evaluate("document.querySelector('.file-preview-close').click()");
 clearTimeout(watchdog);ws.close();console.log('PASS: office preview/search/literal HTML, sheet selection, numeric sorting, filtering, keyboard column resize, responsive mobile/desktop and no JS errors');
})().catch(error=>{console.error(error);process.exit(1)});
