const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const tabs=await(await fetch('http://127.0.0.1:'+ (process.env.SMETRA_CDP_PORT||'9223') +'/json')).json();
 const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let seq=0;const pending=new Map(),errors=[];
 ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)});
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const until=async expression=>{for(let i=0;i<120;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error(expression+'\n'+await evaluate('document.body.innerText'))};
 await send('Runtime.enable');await send('Page.enable');await send('Network.enable');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await send('Page.navigate',{url:'http://localhost:8084/app'});
 await until("document.querySelector('#auth-form')?.onsubmit && document.querySelector('#auth-login-tab')?.onclick");
 await evaluate("document.querySelector('#email').value='android-design@test.invalid';document.querySelector('#password').value='android design test only';document.querySelector('#auth-submit').click()");
 await until("document.querySelector('[data-work=quote-new]')");
 await evaluate("document.querySelector('[data-tab=assistant]').click()");
 await until("document.querySelector('.assistant-diff-total')");
 const before=await evaluate("api('/quotes').then(r=>r.quotes.find(q=>q.title==='Айдентика и упаковка'))");
 assert.equal(before.amount_kopecks,6400000);
 assert.match(await evaluate("document.querySelector('.assistant-edit-diff').innerText"),/64.?000/);
 assert.match(await evaluate("document.querySelector('.assistant-edit-diff').innerText"),/70.?400/);
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 let shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('data/assistant-web-diff.png',Buffer.from(shot.data,'base64'));
 await evaluate("document.querySelector('[data-confirm]').click()");
 await until("[...document.querySelectorAll('#assistant-actions button')].some(b=>b.textContent==='Отменить изменение')");
 assert.equal(await evaluate(`api('/quotes/${before.id}').then(r=>r.quote.amount_kopecks)`),7040000);
 await evaluate('window.SmetraAssistant()');
 await until("document.querySelector('.assistant-saved button')");
 await evaluate("document.querySelector('.assistant-saved button').click()");
 await until("document.querySelector('.assistant-saved').textContent.includes('Изменение отменено')");
 assert.equal(await evaluate(`api('/quotes/${before.id}').then(r=>r.quote.amount_kopecks)`),6400000);
 assert.deepEqual(errors,[]);console.log('PASS: 390px web preview, no overflow, real API apply, reload recovery and undo');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
