const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const watchdog=setTimeout(()=>{console.error('FAIL: browser verification did not finish within 60 seconds');process.exit(1)},60000);
 const tabs=await(await fetch('http://127.0.0.1:'+ (process.env.SMETRA_CDP_PORT||'9223') +'/json')).json();
 const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let seq=0;const pending=new Map(),errors=[];let operation='connecting';
 ws.addEventListener('close',event=>{for(const request of pending.values())request.reject(Error('Browser connection closed during '+operation+' ('+event.code+')'));pending.clear()});
 ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)});
 const send=(method,params={})=>new Promise((resolve,reject)=>{operation=method+' '+String(params.expression||params.url||'').slice(0,100);const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
 const until=async expression=>{for(let i=0;i<120;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error(expression+'\n'+await evaluate('document.body.innerText'))};
 await send('Runtime.enable');await send('Page.enable');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await send('Page.navigate',{url:'http://localhost:8084/app'});
 await until("document.querySelector('#auth-form')?.onsubmit && document.querySelector('#auth-login-tab')?.onclick");
 await evaluate("document.querySelector('#email').value='android-design@test.invalid';document.querySelector('#password').value='android design test only';document.querySelector('#auth-submit').click()");
 await until("document.querySelector('[data-work=quote-new]')");
 await evaluate("document.querySelector('[data-tab=assistant]').click()");
 await until("document.querySelector('.assistant-diff-total')");
 const before=await evaluate("api('/quotes').then(r=>r.quotes.find(q=>q.title==='Айдентика и упаковка'))");
 assert.equal(before.amount_kopecks,6400000);
 assert.match(await evaluate("document.querySelector('.assistant-edit-diff').innerText"),/64.?000/);
 assert.match(await evaluate("document.querySelector('.assistant-edit-diff').innerText"),/70.?400/);
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 let shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('data/assistant-web-diff.png',Buffer.from(shot.data,'base64'));
 await evaluate("document.querySelector('[data-confirm]').click()");
 await until("[...document.querySelectorAll('#assistant-actions button')].some(b=>b.textContent==='Отменить изменение')");
 assert.equal(await evaluate(`api('/quotes/${before.id}').then(r=>r.quote.amount_kopecks)`),7040000);
 await evaluate('window.SmetraAssistant()');
 await until("document.querySelector('.assistant-saved button')");
 await evaluate("document.querySelector('.assistant-saved button').click()");
 await until("document.querySelector('.assistant-saved').textContent.includes('Изменение отменено')");
 assert.equal(await evaluate(`api('/quotes/${before.id}').then(r=>r.quote.amount_kopecks)`),6400000);
 await evaluate(`window.SmetraAssistantContext({entity:'quotes',id:'${before.id}',label:'Айдентика и упаковка',workspace_id:window.Workspace.currentWorkspaceId()});window.SmetraAssistant()`);
 await until("!document.querySelector('#assistant-context').classList.contains('hidden')");
 await evaluate("document.querySelector('#assistant-new-thread').click()");
 await until("document.querySelector('#assistant-thread-select').value!==''");
 const threadId=await evaluate("document.querySelector('#assistant-thread-select').value");
 assert.equal(await evaluate(`api('/assistant/conversations/${threadId}').then(r=>r.conversation.context_id)`),before.id);
 await evaluate('window.SmetraAssistant()');
 await until("document.querySelector('#assistant-context-label').textContent.includes('Айдентика и упаковка')");
 await evaluate("document.querySelector('#assistant-rename').click();document.querySelector('#assistant-thread-name').value='План недели';document.querySelector('#assistant-thread-edit [type=submit]').click()");
 await until("document.querySelector('#assistant-thread-select').selectedOptions[0].textContent==='План недели'");
 await evaluate("document.querySelector('#assistant-pin').click()");
 await until("document.querySelector('#assistant-thread-select').selectedOptions[0].textContent.includes('●')");
 await evaluate("document.querySelector('#assistant-context-remove').click()");
 await until("document.querySelector('#assistant-context').classList.contains('hidden')");
 assert.equal(await evaluate(`api('/assistant/conversations/${threadId}').then(r=>r.conversation.context_id)`),'');
 const second=await evaluate(`api('/assistant/conversations',{method:'POST',body:JSON.stringify({title:'Другой контекст',context_entity:'quotes',context_id:'${before.id}'})}).then(r=>r.conversation.id)`);
 await evaluate('window.SmetraAssistant()');
 await until(`document.querySelector('#assistant-thread-select option[value="${second}"]')`);
 await evaluate(`{const select=document.querySelector('#assistant-thread-select');select.value='${second}';select.dispatchEvent(new Event('change'))}`);
 await until("document.querySelector('#assistant-context-label').textContent.includes('Айдентика и упаковка')");
 await evaluate("{const select=document.querySelector('#assistant-thread-select');select.value='';select.dispatchEvent(new Event('change'))}");
 await until("document.querySelector('#assistant-thread-select').value==='' && document.querySelector('#assistant-context').classList.contains('hidden')");
 const fileThread=await evaluate(`(async()=>{const file=(await api('/files',{method:'POST',body:JSON.stringify({assistant_upload:true,name:'brief.txt',content:btoa('file context')})})).file;return (await api('/assistant/conversations',{method:'POST',body:JSON.stringify({title:'Бриф проекта',context_entity:'files',context_id:file.id})})).conversation.id})()`);
 await evaluate('window.SmetraAssistant()');
 await until(`document.querySelector('#assistant-thread-select option[value="${fileThread}"]')`);
 await evaluate(`{const select=document.querySelector('#assistant-thread-select');select.value='${fileThread}';select.dispatchEvent(new Event('change'))}`);
 await until("document.querySelector('#assistant-context-label').textContent==='Файл: brief.txt'");
 await until("document.querySelector('.assistant-jobbar button')?.hidden===false");
 await evaluate("document.querySelector('#assistant-input').value='Проверь бриф в фоне';document.querySelector('.assistant-jobbar button').click()");
 await until("document.querySelector('.assistant-job strong')?.textContent==='Проверь бриф в фоне'");
 await send('Page.navigate',{url:'http://localhost:8084/app#assistant'});
 await until("[...document.querySelectorAll('.assistant-job button')].some(b=>b.textContent==='Открыть ответ')");
 await evaluate("[...document.querySelectorAll('.assistant-job')].find(r=>r.querySelector('strong').textContent==='Проверь бриф в фоне').querySelector('button').click()");
 await until("document.querySelector('#assistant-messages').textContent.includes('Фоновая задача завершена.')");
 assert.equal(await evaluate("document.querySelector('#assistant-thread-select').value"),fileThread);
 const chooseRetryFile="(()=>{const files=new DataTransfer();files.items.add(new File(['# Retry context'],'retry-web.md',{type:'text/markdown'}));const input=document.querySelector('#assistant-attach-input');input.files=files.files;input.dispatchEvent(new Event('change'))})()";
 await evaluate(chooseRetryFile);
 await until("document.querySelector('#assistant-status').textContent.includes('Тестовая потеря ответа вложения')");
 await send('Page.navigate',{url:'http://localhost:8084/app#assistant'});
 await until("document.querySelector('#assistant-attach-input') && document.querySelector('#assistant-thread-select').value!==''");
 await evaluate(chooseRetryFile);
 await until("document.querySelector('#assistant-context-label').textContent==='Файл: retry-web.md'");
 assert.equal(await evaluate("api('/files').then(result=>result.items.filter(file=>file.name==='retry-web.md').length)"),1);
 const quotaBeforeIndex=await evaluate("api('/assistant').then(result=>result.quota.used)");
 await evaluate("(()=>{const files=new DataTransfer();files.items.add(new File(['Paint walls. '+'a'.repeat(2100000)],'large-web.txt',{type:'text/plain'}));const input=document.querySelector('#assistant-attach-input');input.files=files.files;input.dispatchEvent(new Event('change'))})()");
 await until("document.querySelector('#assistant-context-label').textContent==='Файл: large-web.txt'");
 await evaluate("document.querySelector('#assistant-input').value='Черновик во время подготовки'");
 await until("document.querySelector('.assistant-file-status').textContent.includes('Текст готов')");
 assert.equal(await evaluate("document.querySelector('#assistant-input').value"),'Черновик во время подготовки');
 assert.match(await evaluate("document.querySelector('.assistant-file-status').textContent"),/подготовлена часть текста/);
 assert.equal(await evaluate("api('/assistant').then(result=>result.quota.used)"),quotaBeforeIndex);
 await send('Page.navigate',{url:'http://localhost:8084/app#assistant'});
 await until("document.querySelector('.assistant-file-status')?.textContent.includes('Текст готов')");
 assert.equal(await evaluate("document.querySelector('#assistant-context-label').textContent"),'Файл: large-web.txt');
 shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('data/assistant-web-jobs.png',Buffer.from(shot.data,'base64'));
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
 assert.deepEqual(errors,[]);clearTimeout(watchdog);console.log('PASS: 390px preview, apply/undo, contexts, retries after reload, free background indexing of 2.1MB file, preserved draft during preparation; no overflow or JS errors');ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
