/* Assistant controls, knowledge dialog, profile and Markdown in the CI browser. */
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const timeout=setTimeout(()=>{console.error('FAIL: assistant studio browser timeout');process.exit(1)},90000);
 const site='http://localhost:8084',tabs=await(await fetch('http://127.0.0.1:'+(process.env.SMETRA_CDP_PORT||9223)+'/json')).json();
 const ws=new WebSocket(tabs.find(tab=>tab.type==='page').webSocketDebuggerUrl);await new Promise(resolve=>ws.addEventListener('open',resolve,{once:true}));
 let seq=0;const pending=new Map(),errors=[];
 ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id){const task=pending.get(message.id);pending.delete(message.id);message.error?task.reject(message.error):task.resolve(message.result)}else if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails.text);else if(message.method==='Page.javascriptDialogOpening')send('Page.handleJavaScriptDialog',{accept:true})});
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
 const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value};
 const until=async expression=>{for(let i=0;i<130;i++){if(await evaluate(expression))return;await new Promise(resolve=>setTimeout(resolve,100))}throw Error(expression+'\n'+await evaluate('document.body.innerText'))};
 const screenshot=async name=>fs.writeFileSync('data/assistant-studio-'+name+'.png',Buffer.from((await send('Page.captureScreenshot')).data,'base64'));
 const visit=async tab=>{await evaluate(`document.querySelector('[data-tab="${tab}"]').click()`);await until(`document.querySelector('#content').dataset.section==='${tab}'&&!document.querySelector('#retry')`)};
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Browser.grantPermissions',{origin:site,permissions:['clipboardReadWrite','clipboardSanitizedWrite']});
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Network.deleteCookies',{name:'session',url:site});await send('Page.navigate',{url:site+'/app'});
 await until("document.querySelector('#auth-form')?.onsubmit");await evaluate("document.querySelector('#email').value='android-design@test.invalid';document.querySelector('#password').value='android design test only';document.querySelector('#auth-submit').click()");await until("document.querySelector('.workspace-home')");
 await visit('assistant');await until("document.querySelector('#assistant-input')");await screenshot('welcome-mobile');
 assert.equal(await evaluate("document.querySelector('#assistant-rename').disabled||document.querySelector('#assistant-pin').disabled||document.querySelector('#assistant-delete').disabled"),false);
 await evaluate("document.querySelector('.assistant-options').open=true;document.querySelector('#assistant-rename').click();document.querySelector('#assistant-thread-name').value='Studio conversation';document.querySelector('#assistant-thread-edit').requestSubmit()");await until("document.querySelector('.assistant-current-title').textContent==='Studio conversation'");
 await evaluate("document.querySelector('#assistant-pin').click()");await until("document.querySelector('#assistant-pin').textContent==='Открепить'");await evaluate("document.querySelector('#assistant-pin').click()");await until("document.querySelector('#assistant-pin').textContent==='Закрепить'");
 await evaluate("document.querySelector('#assistant-delete').click()");await until("!sessionStorage.getItem('smetra.assistant.conversation')&&!document.querySelector('#assistant-delete').disabled");
 await evaluate("document.querySelector('#assistant-delete').click()");await until("document.querySelector('#assistant-delete')?.textContent==='Очистить диалог'&&!document.querySelector('#assistant-delete').disabled");
 await evaluate("document.querySelector('#assistant-knowledge').click()");await until("document.querySelector('#assistant-knowledge-panel').open");await screenshot('knowledge-mobile');
 await evaluate("document.querySelector('#knowledge-form [name=title]').value='Studio knowledge';document.querySelector('#knowledge-form [name=content]').value='Ремонт квартир';document.querySelector('#knowledge-form').requestSubmit()");await until("document.querySelector('.knowledge-item')?.textContent.includes('Studio knowledge')");
 await evaluate("document.querySelector('.knowledge-item').click();document.querySelector('#knowledge-form [name=content]').value='Ремонт и отделка';document.querySelector('#knowledge-form').requestSubmit()");await until("document.querySelector('.knowledge-item')?.textContent.includes('Ремонт и отделка')");
 await evaluate("document.querySelector('[data-knowledge-scope=workspace]').click()");await until("document.querySelector('[data-knowledge-scope=workspace]').getAttribute('aria-pressed')==='true'");await evaluate("document.querySelector('[data-knowledge-scope=personal]').click()");await until("document.querySelector('.knowledge-item')?.textContent.includes('Studio knowledge')");
 await evaluate("document.querySelector('.knowledge-item').click();document.querySelector('#knowledge-delete').click()");await until("!document.querySelector('.knowledge-item')");await evaluate("document.querySelector('#knowledge-close').click()");await until("!document.querySelector('#assistant-knowledge-panel').open");
 await visit('profile');await until("document.querySelector('#profile-form')");await evaluate("document.querySelector('#profile-form [name=first_name]').value='Анна';document.querySelector('#profile-form [name=last_name]').value='Смирнова';document.querySelector('#profile-form [name=profession]').value='Дизайнер интерьера';document.querySelector('#profile-form [name=about]').value='Проектирую жилые пространства';document.querySelector('#profile-form').requestSubmit()");await until("document.querySelector('#profile-form [role=status]').textContent==='Сохранено'");assert.equal(await evaluate("user.name"),'Анна Смирнова');await screenshot('profile-mobile');
 await visit('settings');await until("document.querySelector('#personalization-form')");await evaluate("document.querySelector('[name=memory_enabled]').checked=false;document.querySelector('[name=response_style]').value='detailed';document.querySelector('#personalization-form').requestSubmit()");await until("document.querySelector('#personalization-form [role=status]').textContent==='Сохранено'");assert.equal(await evaluate("api('/profile').then(r=>r.profile.memory_enabled)"),0);
 await evaluate("document.querySelector('[name=memory_enabled]').checked=true;document.querySelector('#personalization-form').requestSubmit()");await until("api('/profile').then(r=>r.profile.memory_enabled===1)");
 await visit('assistant');await until("document.querySelector('#assistant-input')");
 const markdown='# План проекта\n\n**Проверенные данные** и *следующие шаги*.\n\n3. Подготовить смету\n   - Сверить объёмы\n   - Уточнить материалы\n4. Согласовать работы\n\n- [x] Замеры готовы\n- [ ] Смета согласована\n\n| Работа | Стоимость |\n| :--- | ---: |\n| Подготовка | 12 000 ₽ |\n| Отделка | 48 000 ₽ |\n\n> Итоговую цену согласовываем с клиентом.\n\n```json\n{"status": "draft", "test": "<img>"}\n```';
 await evaluate(`document.querySelector('#assistant-messages').innerHTML='<article class="assistant-message assistant"><small>СМЕТРА</small><div class="assistant-markdown">'+assistantMarkdown(${JSON.stringify(markdown)})+'</div></article>'`);
 assert.equal(await evaluate("document.querySelectorAll('.assistant-markdown img, .assistant-markdown script').length"),0);assert.equal(await evaluate("document.querySelector('ol').start"),3);
 await evaluate("document.querySelector('[data-copy-code]').click()");await until("document.querySelector('[data-copy-code]').textContent==='Скопировано'");assert.ok((await evaluate('navigator.clipboard.readText()')).includes('"test": "<img>"'));
 for(const width of [320,390,1440]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<700});await evaluate('window.scrollTo(0,0)');await new Promise(resolve=>setTimeout(resolve,150));assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,'Assistant overflow '+width);await screenshot('markdown-'+width)}
 assert.deepEqual(errors,[]);clearTimeout(timeout);ws.close();console.log('PASS: general rename/pin/unpin/delete, knowledge dialog CRUD/scopes, profile/settings, nested Markdown/code copy and 320/390/1440px layout; no browser errors');
})().catch(error=>{console.error(error);process.exit(1)});
