/* Requires an isolated Chrome and a disposable server; ports are configurable for PostgreSQL QA. */
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async () => {
  const site = 'http://localhost:' + (process.env.SMETRA_TEST_PORT || '8082');
  const debuggerUrl = 'http://127.0.0.1:' + (process.env.SMETRA_CDP_PORT || '9223') + '/json';
  const tabs = await (await fetch(debuggerUrl)).json();
  const ws = new WebSocket(tabs.find(t => t.type === 'page').webSocketDebuggerUrl);
  await new Promise(resolve => ws.addEventListener('open', resolve, {once:true}));
  let seq=0;const pending=new Map(), errors=[];
  ws.addEventListener('message',ev=>{const m=JSON.parse(ev.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text)});
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  const until=async expression=>{for(let n=0;n<80;n++){if(await evaluate(expression))return;await wait(100)}throw Error('Timeout: '+expression+'\n'+await evaluate('document.body.innerText.slice(-1600)'))};
  const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const fill=(selector,value)=>evaluate(`{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}`);
  const shot=async name=>{fs.mkdirSync('data/qa',{recursive:true});fs.writeFileSync('data/qa/'+name+'.png',Buffer.from((await send('Page.captureScreenshot')).data,'base64'))};
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Network.setCacheDisabled',{cacheDisabled:true});
  await send('Network.deleteCookies',{name:'session',url:site});
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1050,deviceScaleFactor:1,mobile:false});
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
  await send('Page.navigate',{url:site+'/app?register=1'});
  await until("document.querySelector('#auth')&&!document.querySelector('#auth').classList.contains('hidden')");
  await fill('#name','Проверка продукта');await fill('#email','browser-'+Date.now()+'@test.invalid');await fill('#password','long secure password');await click('#auth-submit');
  await until("document.querySelector('[data-work=quote-new]')");
  await shot('workspace-dashboard');
  await click('[data-tab=clients]');await until("document.querySelector('[data-work=new]')");await click('[data-work=new]');await until("document.querySelector('#f-company')");await fill('#f-name','Тестовый клиент');await fill('#f-company','Тестовая компания');await click('#entity-form [type=submit]');
  await until("!document.querySelector('#workspace-dialog')?.open && document.querySelector('#records')?.textContent.includes('Тестовый клиент')");
  await click('[data-tab=catalog]');await until("document.querySelector('#catalog-category')");await click('[data-work=new]');await until("document.querySelector('#f-price')");
  await fill('#f-name','Покраска стен');await fill('#f-price','1200');await fill('#f-category','Отделка');await click('#entity-form [type=submit]');
  await until("!document.querySelector('#workspace-dialog')?.open && document.querySelector('#records')?.textContent.includes('Покраска стен')");
  await click('[data-work=catalog-favorite]');await until("document.querySelector('[data-work=catalog-favorite][aria-pressed=true]')");
  await click('#catalog-favorites');await until("document.querySelector('#records')?.textContent.includes('Покраска стен')");
  await click('.catalog-row [data-work=entity]');await until("document.querySelector('.catalog-detail-price')");
  await click('[data-work=catalog-edit]');await until("document.querySelector('#workspace-dialog')?.open && document.querySelector('.dialog-heading h2')?.textContent==='Редактирование'");await fill('#f-price','1400');await click('#entity-form [type=submit]');
  await until("!document.querySelector('#workspace-dialog')?.open && document.querySelectorAll('.catalog-history-row').length===2");
  assert.match(await evaluate("document.querySelector('.catalog-detail-price').textContent"),/1.?400/);await shot('catalog-price-history');
  await click('[data-work=navigate]');await until("document.querySelector('.catalog-row')");await click('[data-work=new]');await until("document.querySelector('#workspace-dialog')?.open");
  await fill('#f-name','Покраска стен');await fill('#f-price','1400');await click('#entity-form [type=submit]');await until("document.querySelector('#catalog-duplicate-override')");
  assert.equal(await evaluate("api('/catalog').then(r=>r.items.length)"),1);await click('#workspace-dialog [data-cancel]');await until("!document.querySelector('#workspace-dialog')?.open");
  await click('[data-work=import]');await until("document.querySelector('#f-input_format')");await fill('#f-csv','Название\tЦена\tСебестоимость\tЕдиница\tКатегория\nШтукатурка\t250,50\t120\tм²\tОтделка');await click('#workspace-dialog [type=submit]');
  await until("!document.querySelector('#workspace-dialog')?.open && document.querySelector('#records')?.textContent.includes('Штукатурка')");
  assert.equal(await evaluate("api('/catalog?q='+encodeURIComponent('Штукатурка')).then(r=>r.items[0].price)"),25050);
  await click('[data-tab=quotes]');await until("document.querySelector('[data-work=quote-new]')");await click('[data-work=quote-new]');await until("document.querySelector('#estimate-editor')");
  await fill('#catalog-search','Штукатурка');await until("document.querySelector('#f-catalog')?.options.length===2 && document.querySelector('#f-catalog')?.options[1].textContent.includes('Штукатурка')");
  await evaluate("{const s=document.querySelector('#f-catalog');s.selectedIndex=1;s.dispatchEvent(new Event('change',{bubbles:true}))}");
  assert.match(await evaluate("document.querySelector('[data-row=\"1\"] [data-key=name]').value"),/Штукатурка/);await click('[data-remove="1"]');
  await fill('#f-title','Проверка полного цикла');await evaluate("{const s=document.querySelector('#f-client_id');s.selectedIndex=1;s.dispatchEvent(new Event('change'))}");
  await fill('[data-row="0"] [data-key=name]','Работа по проекту');await fill('[data-row="0"] [data-key=quantity]','2.5');await fill('[data-row="0"] [data-key=unit_price]','1200');await fill('[data-row="0"] [data-key=cost_price]','400');
  assert.match(await evaluate("document.querySelector('#editor-total').textContent"),/3.?000/);
  await click('#add-row');await fill('[data-row="1"] [data-key=name]','Материалы для проекта');await fill('[data-row="1"] [data-key=quantity]','1');await fill('[data-row="1"] [data-key=unit_price]','500');
  await click('#editor-bulk-all');await evaluate("document.querySelector('#editor-bulk-field').value='markup'");await fill('#editor-bulk-value','10');await click('#editor-bulk-preview');
  await until("document.querySelector('#editor-bulk-apply')");assert.match(await evaluate("document.querySelector('#editor-bulk-diff').innerText"),/3.?850/);
  await click('#editor-bulk-apply');assert.match(await evaluate("document.querySelector('#editor-total').textContent"),/3.?850/);
  await click('#editor-bulk-undo');assert.match(await evaluate("document.querySelector('#editor-total').textContent"),/3.?500/);
  await click('#editor-bulk-preview');await click('#editor-bulk-apply');
  assert.equal(await evaluate("api('/quotes').then(result=>result.quotes.length)"),0);
  await shot('estimate-editor');await click('#estimate-editor [type=submit]');await until("document.querySelector('#quote-controls')");
  await click('#quote-controls [data-work=publish]');await until("document.querySelector('#workspace-dialog')?.open");await click('#workspace-dialog [type=submit]');await until("!document.querySelector('#workspace-dialog')?.open && document.querySelector('#quote-controls [data-work=link]')");
  const quote=await evaluate("api('/quotes').then(r=>r.quotes[0])");
  await send('Page.navigate',{url:quote.public_url});await until("document.querySelector('#client-response')");
  await wait(400);await shot('client-portal');await fill('#client-response [name=name]','Тестовый клиент');await click('#client-response [type=submit]');await until("document.querySelector('#public-quote').textContent.includes('Условия согласованы')");
  await send('Page.navigate',{url:site+'/app#quotes'});await until("document.querySelector('[data-work=quote]')");await click('[data-work=quote]');await until("document.querySelector('#quote-controls [data-work=project]')");await click('#quote-controls [data-work=project]');await until("document.querySelector('#project-receipt')");
  await click('#project-receipt');await until("document.querySelector('#workspace-dialog')?.open");await fill('#f-amount_kopecks','1000');await click('#workspace-dialog [type=submit]');await until("!document.querySelector('#workspace-dialog')?.open");
  assert.match(await evaluate("document.querySelector('#content').textContent"),/1.?000/);
  await shot('project-payment');
  await click('[data-tab=documents]');await until("document.querySelector('[data-work=document]')");await click('[data-work=document]');await until("document.querySelector('#workspace-dialog')?.open");await click('#workspace-dialog [type=submit]');await until("!document.querySelector('#workspace-dialog')?.open && document.querySelector('[data-work=download-document]')");
  await click('[data-tab=finance]');await until("document.querySelector('#content').textContent.includes('Денежный результат')");await shot('finance');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await wait(300);assert.equal(await evaluate('document.documentElement.scrollWidth'),390);await shot('mobile-finance');
  await click('[data-tab=catalog]');await until("document.querySelector('.catalog-row')");await evaluate("[...document.querySelectorAll('.catalog-row [data-work=entity]')].find(b=>b.textContent.includes('Покраска стен')).click()");await until("document.querySelectorAll('.catalog-history-row').length===2");assert.equal(await evaluate('document.documentElement.scrollWidth'),390);await shot('mobile-catalog-history');
  await click('[data-tab=quotes]');await until("document.querySelector('[data-work=quote-new]')");await click('[data-work=quote-new]');await until("document.querySelector('#estimate-editor')");assert.equal(await evaluate('document.documentElement.scrollWidth'),390);await shot('mobile-editor');await evaluate("document.querySelector('#editor-bulk').scrollIntoView({block:'start'})");await wait(200);assert.equal(await evaluate('document.documentElement.scrollWidth'),390);await shot('mobile-editor-bulk');
  await evaluate("Workspace.palette()");await until("document.querySelector('#command-search')");await fill('#command-search','Тестовый');await until("document.querySelector('#command-results').textContent.includes('Тестовый клиент')");await shot('mobile-search');
  const intakeUrl=await evaluate("api('/intake',{method:'POST'}).then(r=>r.form.public_url)");
  await send('Page.navigate',{url:intakeUrl});await until("document.querySelector('#client-intake')");await shot('client-intake-form-mobile');
  assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
  await fill('#f-name','Заявка с сайта');await fill('#f-email','request@example.ru');await fill('#f-details','Нужен сайт для мастерской');await fill('#f-budget','25000');await click('#client-intake [type=submit]');
  await until("document.querySelector('#public-quote').textContent.includes('ЗАЯВКА ОТПРАВЛЕНА')");await shot('client-intake-mobile');
  await send('Page.navigate',{url:site+'/app#leads'});await until("document.querySelector('#records')?.textContent.includes('Заявка с сайта')");
  assert.deepEqual(errors,[]);console.log('PASS: registration → client → bulk editor preview/undo → quote → approval → project → payment → PDF; public intake → lead; desktop/mobile layout; no browser exceptions');ws.close();
})().catch(err=>{console.error(err);process.exit(1)});
