/* Real authenticated API + shipped DOM handlers, isolated SQLite/provider fixture. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {spawn}=require('node:child_process'),{JSDOM,VirtualConsole}=require(process.env.SMETRA_JSDOM_MODULE||'jsdom');
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const port=Number(process.env.SMETRA_ACTION_PORT||8095),origin='http://localhost:'+port;
const folder=process.env.SMETRA_QA_DIR||'data/qa';fs.mkdirSync(folder,{recursive:true});
const serverLog=fs.createWriteStream(path.join(folder,'app-actions-server.log'));
const child=spawn(process.env.SMETRA_TEST_PYTHON||'python',['scripts/android_ui_fixture.py'],{env:{...process.env,SMETRA_FIXTURE_PORT:String(port),SMETRA_ACTION_QA:'1'},windowsHide:true});
child.stdout.pipe(serverLog);child.stderr.pipe(serverLog);
let dom;const errors=[],actions=[],downloads=[];
const watchdog=setTimeout(()=>{console.error('FAIL: action verification timeout');child.kill();process.exit(1)},180000);
async function ready(){await new Promise((resolve,reject)=>{let text='';child.stdout.on('data',chunk=>{text+=chunk;if(text.includes('ANDROID_UI_FIXTURE_READY'))resolve()});child.on('exit',code=>reject(Error('Fixture stopped: '+code)))})}
(async()=>{
 await ready();const vc=new VirtualConsole();vc.on('jsdomError',error=>{if(!error.message.includes('navigation'))errors.push(error.message)});
 dom=new JSDOM(fs.readFileSync('apps/web/app.html','utf8'),{url:origin+'/app',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc});
 const w=dom.window,doc=w.document;let cookies='',clipboard='';
 w.matchMedia=query=>({matches:query.includes('prefers-reduced-motion')||query.includes('max-width:700px'),addEventListener(){}});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>false;w.alert=message=>errors.push('alert: '+message);w.TextDecoder=TextDecoder;w.TextEncoder=TextEncoder;w.AbortController=AbortController;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;w.setTimeout(()=>this.dispatchEvent(new w.Event('close')),0)};
 w.URL.createObjectURL=blob=>{downloads.push(blob);return 'blob:'+origin+'/qa-'+downloads.length};w.URL.revokeObjectURL=()=>{};
 w.HTMLAnchorElement.prototype.click=function(){actions.push({page:doc.querySelector('#content')?.dataset.section,download:this.download,href:this.href})};
 Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>{clipboard=text}}});
 Object.defineProperty(w.HTMLElement.prototype,'innerText',{get(){return this.textContent},set(value){this.textContent=value}});
 w.fetch=async(url,options={})=>{const target=new URL(url,origin);assert.equal(target.origin,origin,'Fixture must never call another service');const response=await fetch(target,{...options,headers:{...options.headers,Origin:origin,...(cookies?{Cookie:cookies}:{})}});for(const cookie of response.headers.getSetCookie()){const entry=cookie.split(';')[0];cookies=entry}return response};
 const load=file=>{const script=doc.createElement('script');script.textContent=fs.readFileSync('apps/web/'+file,'utf8');doc.head.append(script)};
 ['theme-init.js','app.js','workspace.js','black.js','assistant-chat.js','ai-workspace.js','admin.js','file-preview.js','construction.js','file-editor.js','product-ui.js'].forEach(load);
 async function until(check,label){for(let i=0;i<400;i++){if(check())return;await pause(20)}throw Error(label+'; '+doc.querySelector('#content').textContent.slice(-650)+'; modal: '+doc.querySelector('#workspace-dialog')?.textContent.slice(-300)+'; file: '+doc.querySelector('.file-preview-body')?.textContent)}
 const query=selector=>{const node=doc.querySelector(selector);assert.ok(node,'Missing '+selector);return node};
 const fill=(selector,value)=>{const node=query(selector);node.value=value;node.dispatchEvent(new w.Event('input',{bubbles:true}));node.dispatchEvent(new w.Event('change',{bubbles:true}));return node};
 function click(selector){const node=typeof selector==='string'?query(selector):selector;assert.ok(node);assert.equal(node.disabled,false,'Disabled: '+node.textContent);actions.push({page:doc.querySelector('#content').dataset.section,label:node.textContent.trim()||node.getAttribute('aria-label'),id:node.id,action:node.dataset.work});node.click();return node}
 async function visit(section){click('[data-tab="'+section+'"]');await until(()=>doc.querySelector('#content').dataset.section===section,'Visit '+section);assert.ok(!doc.querySelector('#retry'),'Page failed: '+section);await pause(25)}
 async function modal(selector){click(selector);await until(()=>doc.querySelector('#workspace-dialog')?.open,'Open dialog '+selector)}
 const dismiss=async()=>{click('#workspace-dialog [data-cancel],#workspace-dialog [data-close]');await until(()=>!doc.querySelector('#workspace-dialog').open,'Dismiss dialog')};
 async function submit(selector){const form=query(selector);assert.equal(form.checkValidity(),true,'Invalid form: '+selector+' '+[...form.elements].filter(node=>node.willValidate&&!node.checkValidity()).map(node=>node.name+': '+node.validationMessage).join('; '));actions.push({page:doc.querySelector('#content').dataset.section,submit:selector});form.requestSubmit()}
 await until(()=>doc.querySelector('#auth-form').onsubmit,'Boot');await until(()=>doc.querySelector('#forgot').classList.contains('hidden'),'Unavailable email reset hidden');fill('#email','android-design@test.invalid');fill('#password','android design test only');click('#auth-submit');await until(()=>doc.querySelector('[data-work=quote-new]'),'Login');
 for(const section of ['dashboard','clients','quotes','projects','construction','leads','tasks','calendar','assistant','finance','catalog','files','documents','team','notifications','billing','support','settings','admin'])await visit(section);
 console.log('PASS: all 19 navigation destinations load through their buttons');
 await visit('settings');click('#theme-alt');assert.equal(doc.documentElement.dataset.theme,'light');click('#theme-alt');assert.equal(doc.documentElement.dataset.theme,'dark');click('#delete-account');assert.ok(doc.querySelector('#delete-account'));
 click('#sidebar-collapse');assert.ok(doc.body.classList.contains('sidebar-compact'));click('#sidebar-collapse');assert.ok(!doc.body.classList.contains('sidebar-compact'));
 click('#command-open');await until(()=>doc.querySelector('#workspace-dialog')?.open,'Command palette');await dismiss();
 console.log('PASS: theme, sidebar, palette and account deletion cancellation');
 for(const kind of ['clients','catalog','projects','tasks','leads']){
  await visit(kind);await modal('[data-work=new]');fill('#f-name','UI '+kind);if(kind==='catalog')fill('#f-price','123.45');await submit('#workspace-dialog form');await until(()=>!doc.querySelector('#workspace-dialog').open,'Save '+kind);
  const row=(await w.api('/'+kind)).items.find(item=>item.name==='UI '+kind);assert.ok(row,'Created '+kind);assert.equal(doc.querySelector('#records').textContent.includes('UI '+kind),true);
  console.log('PASS: '+kind+' add button persists the entity');
 }
 await visit('catalog');await modal('[data-work=import]');assert.ok(doc.querySelector('#f-csv'));fill('#f-input_format','csv');fill('#f-csv','name,price,unit\nUI imported,2500,pcs');await submit('#workspace-dialog form');await until(()=>!doc.querySelector('#workspace-dialog').open,'Catalog import');assert.ok((await w.api('/catalog')).items.some(item=>item.name==='UI imported'));
 click('[data-work=export]');await until(()=>downloads.length>0,'Catalog download');assert.ok((await downloads.at(-1).text()).includes('UI imported'));
 const favorite=query('.catalog-row [data-work=catalog-favorite]');click(favorite);await pause(100);assert.ok((await w.api('/catalog')).items.some(item=>item.favorite));
 console.log('PASS: catalog import, actual CSV export and favorite');
 for(const kind of ['clients','catalog','projects','tasks','leads']){
  await visit(kind);const item=(await w.api('/'+kind)).items.find(row=>row.name==='UI '+kind);click('[data-work=entity][data-id="'+item.id+'"]');
  if(kind==='clients'||kind==='projects'){await until(()=>doc.querySelector('#edit-entity'),'Entity detail');await modal('#edit-entity')}
  else if(kind==='catalog'){await until(()=>doc.querySelector('[data-work=catalog-edit]'),'Catalog detail');await modal('[data-work=catalog-edit]')}
  else await until(()=>doc.querySelector('#workspace-dialog')?.open,'Entity edit');
  fill('#f-name','UI '+kind+' edited');await submit('#workspace-dialog form');await until(()=>!doc.querySelector('#workspace-dialog').open,'Edit '+kind);assert.equal((await w.api('/'+kind+'/'+item.id)).item.name,'UI '+kind+' edited');
 }
 await visit('notifications');click('[data-work=read-notifications]');await until(()=>!doc.querySelector('.unread'),'Read notifications');
 console.log('PASS: client, catalog, project, task and lead edits and notification acknowledgement');
 await visit('quotes');click('[data-work=quote-new]');await until(()=>doc.querySelector('#estimate-editor'),'Quote editor');fill('#f-title','UI quote');
 const client=query('#f-client_id');client.value=[...client.options].find(option=>option.value)?.value||'';client.dispatchEvent(new w.Event('change',{bubbles:true}));
 fill('[data-row="0"] [data-key=name]','UI work');fill('[data-row="0"] [data-key=unit_price]','20');click('#add-row');assert.equal(doc.querySelectorAll('[data-row]').length,2);click('[data-remove="1"]');assert.equal(doc.querySelectorAll('[data-row]').length,1);
 click('#editor-bulk-all');fill('#editor-bulk-value','1.1');click('#editor-bulk-preview');click('#editor-bulk-apply');assert.equal(query('[data-row="0"] [data-key=coefficient]').value,'1.1');click('#editor-bulk-undo');assert.equal(Number(query('[data-row="0"] [data-key=coefficient]').value),1);
 click('#local-draft');fill('#f-title','Changed title');click('#restore-draft');assert.equal(query('#f-title').value,'UI quote');
 await submit('#estimate-editor');await until(()=>doc.querySelector('#quote-controls'),'Save quote');const quote=(await w.api('/quotes')).quotes.find(item=>item.title==='UI quote');assert.ok(quote);assert.equal(quote.amount_kopecks,2000);click('[data-work=navigate][data-id=quotes]');await until(()=>doc.querySelector('[data-work=quote-new]'),'Return to quotes');
 click('[data-work=quote][data-id="'+quote.id+'"]');await until(()=>doc.querySelector('#quote-controls'),'Quote detail');await modal('#quote-controls [data-work=publish]');await submit('#workspace-dialog form');await until(()=>doc.querySelector('#quote-controls [data-work=link]')&&!doc.querySelector('#workspace-dialog').open,'Publish quote');click('#quote-controls [data-work=link]');await until(()=>clipboard.includes('quote='),'Copy customer URL');
 await modal('#quote-controls [data-work=document]');await submit('#workspace-dialog form');await until(()=>doc.querySelector('[data-work=download-document]')&&!doc.querySelector('#workspace-dialog').open,'Create document');const before=downloads.length;click('[data-work=download-document]');await until(()=>downloads.length>before,'PDF export');assert.equal((await downloads.at(-1).text()).slice(0,4),'%PDF');
 console.log('PASS: quote rows, local save/restore, persistent save, publication, client URL and actual PDF');
 await visit('finance');for(const kind of ['receipts','expenses']){await modal('[data-work=money][data-id="'+kind+'"]');fill('#f-project_id',(await w.api('/projects')).items.find(item=>item.amount_kopecks>0).id);fill('#f-comment','UI '+kind);fill('#f-amount_kopecks','12.50');if(kind==='expenses')fill('#f-category','UI');await submit('#workspace-dialog form');await until(()=>!doc.querySelector('#workspace-dialog').open,'Save '+kind);assert.ok((await w.api('/'+kind)).items.some(item=>item.comment==='UI '+kind&&item.amount_kopecks===1250))}
 console.log('PASS: income and expense buttons record real amounts');
 await visit('team');await modal('[data-work=member]');fill('#f-email','ui-member@test.invalid');await submit('#workspace-dialog form');await until(()=>doc.querySelector('[data-work=remove-member]')&&!doc.querySelector('#workspace-dialog').open,'Member added');assert.ok((await w.api('/workspace/members')).items.some(item=>item.email==='ui-member@test.invalid'));await modal('[data-work=remove-member]');await submit('#workspace-dialog form');await until(()=>!doc.querySelector('[data-work=remove-member]'),'Member removed');
 await until(()=>doc.querySelector('#new-custom-field'),'Custom fields');await modal('#new-custom-field');fill('#f-name','UI field');await submit('#workspace-dialog form');await until(()=>!doc.querySelector('#workspace-dialog').open,'Custom field save');assert.ok((await w.api('/custom-fields')).items.some(item=>item.name==='UI field'));
 fill('#workspace-f-company_details','UI company');await submit('#workspace-settings');await until(()=>doc.querySelector('#toast').textContent==='Настройки сохранены','Business settings');assert.equal((await w.api('/workspace')).workspace.settings.company_details,'UI company');
 console.log('PASS: team dialog, custom fields and business settings');
 await visit('support');click('[data-support-topic="Работа со сметой"]');fill('#message','UI support request');await submit('#support-form');await until(()=>query('#message').value==='','Support saved');
 await visit('billing');click('#sync');await until(()=>doc.querySelector('#toast').textContent.includes('Про активен'),'Billing sync');
 await visit('admin');for(const section of ['support','payments','audit','users']){click('[data-admin-section="'+section+'"]');await pause(100);assert.ok(doc.querySelector('#admin-section').textContent.trim())}
 click('[data-admin-section=support]');await until(()=>doc.querySelector('[data-admin-ticket]'),'Support ticket');
 const ticket=query('[data-admin-ticket]'),ticketId=ticket.dataset.adminTicket;click(ticket);await until(()=>!doc.querySelector('[data-admin-ticket="'+ticketId+'"]'),'Close ticket');
 click('[data-admin-support-filter=closed]');await until(()=>doc.querySelector('[data-admin-ticket="'+ticketId+'"]'),'Closed tickets');click('[data-admin-ticket="'+ticketId+'"]');await until(()=>!doc.querySelector('[data-admin-ticket="'+ticketId+'"]'),'Reopen ticket');
 const fetchBeforeFailure=w.fetch;let failedRefresh=0;
 w.fetch=async(url,options)=>{if(String(url).endsWith('/admin/overview')){failedRefresh++;await pause(30);return new Response(JSON.stringify({error:'QA refresh unavailable'}),{status:503,headers:{'Content-Type':'application/json'}})}return fetchBeforeFailure(url,options)};
 const refresh=click('[data-admin-refresh]');refresh.click();await until(()=>!refresh.disabled,'Admin failed refresh enables retry');assert.equal(failedRefresh,1);assert.match(doc.querySelector('#toast').textContent,/QA refresh/);w.fetch=fetchBeforeFailure;
 click('[data-admin-refresh]');await until(()=>doc.querySelector('[data-admin-refresh]')!==refresh,'Admin refresh success');click('[data-admin-section=users]');await until(()=>doc.querySelector('[data-admin-manage]'),'Admin users');
 click('[data-admin-manage]');await until(()=>doc.querySelector('.admin-dialog')?.open,'Admin manage');click('[data-dialog-close]');await until(()=>!doc.querySelector('.admin-dialog').open,'Admin close');
 const memberId=(await w.api('/admin/users?q=ui-member')).users[0].id;
 for(const action of ['block','unblock','grant','revoke']){await until(()=>doc.querySelector('[data-admin-manage="'+memberId+'"]'),'Admin ready');click('[data-admin-manage="'+memberId+'"]');await until(()=>doc.querySelector('.admin-dialog')?.open,'Admin member');fill('#admin-reason','Isolated action audit');click('[data-admin-action="'+action+'"]');await until(()=>!doc.querySelector('.admin-dialog').open,'Admin '+action);await until(()=>doc.querySelector('[data-admin-manage="'+memberId+'"]'),'Admin list refreshed');const member=(await w.api('/admin/users?q=ui-member')).users[0];if(action==='block'||action==='unblock')assert.equal(Boolean(member.blocked),action==='block');else assert.equal(member.entitlement_until>Date.now()/1000,action==='grant')}
 console.log('PASS: support submission, billing sync and all administrator tabs/dialog');
 await visit('files');click('#file-new-note');await until(()=>doc.querySelector('#file-editor-form'),'New note');fill('#file-editor-form [name=name]','UI note');fill('#file-editor-text','# Original\n\nUI content');assert.match(query('#file-editor-render').innerHTML,/<h[1-6]>Original/);await submit('#file-editor-form');await until(()=>doc.querySelector('#file-center-list'),'Note saved');
 let note=(await w.api('/files')).items.find(item=>item.name==='UI note.md');assert.ok(note);
 click('[data-file-open="'+note.id+'"]');await until(()=>doc.querySelector('.file-preview-save:not([disabled])'),'File preview');assert.match(doc.querySelector('.file-preview-body').textContent,/Original/);click('.file-preview-close');await until(()=>!doc.querySelector('.file-preview-dialog').open,'Close file');
 click('[data-file-edit="'+note.id+'"]');await until(()=>doc.querySelector('#file-editor-form'),'Edit note');fill('#file-editor-text','# Changed\n\nNew content');await submit('#file-editor-form');await until(()=>doc.querySelector('#file-center-list'),'Save edited note');
 click('[data-file-edit="'+note.id+'"]');await until(()=>doc.querySelector('.file-editor-version'),'File versions');click('.file-editor-version');await until(()=>!query('#file-editor-restore').hidden,'Select version');click('#file-editor-restore');await until(()=>query('#file-editor-text').value.includes('Original'),'Restore file version');
 click('#file-editor-history-refresh');await until(()=>doc.querySelector('.file-editor-version'),'Refresh versions');click('#file-editor-back');await until(()=>doc.querySelector('#file-center-list'),'Back to files');
 await modal('[data-file-manage="'+note.id+'"]');fill('#workspace-dialog [name=name]','UI renamed.md');await submit('#workspace-dialog form');await until(()=>!doc.querySelector('#workspace-dialog').open,'File metadata saved');assert.equal((await w.api('/files/'+note.id+'/metadata')).file.name,'UI renamed.md');
 console.log('PASS: Markdown note create, preview, edit, history and restore');
 await visit('assistant');const priorThread=w.sessionStorage.getItem('smetra.assistant.conversation');click('#assistant-new-thread');await until(()=>w.sessionStorage.getItem('smetra.assistant.conversation')!==priorThread&&!query('#assistant-new-thread').disabled,'New conversation');click('#assistant-rename');fill('#assistant-thread-name','UI conversation');await submit('#assistant-thread-edit');await until(()=>[...doc.querySelectorAll('[data-conversation]')].some(item=>item.textContent.includes('UI conversation')),'Rename conversation');
 click('#assistant-pin');await until(()=>query('#assistant-pin').textContent.includes('Открепить'),'Pin conversation');click('#assistant-pin');await until(()=>query('#assistant-pin').textContent.includes('Закрепить'),'Unpin conversation');
 click('#assistant-knowledge');await until(()=>doc.querySelector('#knowledge-form'),'Knowledge');fill('#knowledge-form [name=title]','UI knowledge');fill('#knowledge-form [name=content]','UI rule content');await submit('#knowledge-form');await until(()=>doc.querySelector('.knowledge-item')?.textContent.includes('UI knowledge'),'Knowledge saved');
 click('.knowledge-item');fill('#knowledge-form [name=content]','Updated rule');await submit('#knowledge-form');await until(()=>doc.querySelector('.knowledge-item')?.textContent.includes('Updated rule'),'Knowledge updated');click('#knowledge-reset');assert.equal(query('#knowledge-form [name=title]').value,'');click('.knowledge-item');w.confirm=()=>true;click('#knowledge-delete');await until(()=>!doc.querySelector('.knowledge-item'),'Knowledge deleted');w.confirm=()=>false;click('#knowledge-close');assert.equal(query('#assistant-knowledge').getAttribute('aria-expanded'),'false');
 fill('#assistant-input','UI streaming question');click('#assistant-send');await until(()=>doc.querySelector('.assistant-message.assistant .assistant-copy')&&query('#assistant-stop').hidden,'Streamed reply');assert.match(query('.assistant-message.assistant .assistant-markdown').textContent,/Контекст не выбран/);click('.assistant-copy');await until(()=>clipboard.includes('Контекст не выбран'),'Copy assistant reply');
 fill('#assistant-input','UI slow question');click('#assistant-send');await until(()=>query('#assistant-messages').textContent.includes('Тестовый поток начат'),'Partial stream');click('#assistant-stop');await until(()=>query('#assistant-stop').hidden,'Stop stream');assert.equal(query('#assistant-input').value,'UI slow question');assert.match(query('#assistant-status').textContent,/остановлен/);
 await visit('settings');await visit('assistant');await until(()=>doc.querySelector('.assistant-fork'),'Conversation history');const beforeFork=w.sessionStorage.getItem('smetra.assistant.conversation'),beforeForkDelete=query('#assistant-delete');click('.assistant-fork');await until(()=>w.sessionStorage.getItem('smetra.assistant.conversation')!==beforeFork&&query('#assistant-delete')!==beforeForkDelete&&doc.querySelector('.assistant-fork'),'Fork conversation');
 const uiConversationId=w.sessionStorage.getItem('smetra.assistant.conversation');
 w.confirm=()=>true;const deletedConversationButton=click('#assistant-delete');await until(()=>query('#assistant-delete')!==deletedConversationButton&&query('#assistant-delete').disabled,'Delete conversation');w.confirm=()=>false;assert.ok(!(await w.api('/assistant/conversations')).items.some(item=>item.id===uiConversationId));
 await until(()=>!query('#assistant-background').hidden,'Worker mode available');click('#assistant-background');fill('#assistant-input','UI background question');click('#assistant-send');await until(()=>doc.querySelector('.assistant-job[data-status=completed] button'),'Background reply saved');click('.assistant-job[data-status=completed] button');await until(()=>[...doc.querySelectorAll('.assistant-message.assistant')].some(item=>item.textContent.includes('Фоновая задача завершена')),'Open background reply');
 console.log('PASS: conversation create, rename, pin, unpin, delete and knowledge CRUD');
 await visit('construction');fill('#construction-new [name=name]','UI object');await submit('#construction-new');await until(()=>doc.querySelector('#construction-zone'),'Construction object');assert.ok((await w.api('/construction/objects')).items.some(item=>item.name==='UI object'));
 const object=(await w.api('/construction/objects')).items.find(item=>item.name==='UI object'),objectPath='/construction/objects/'+object.id;
 const objectData=()=>w.api(objectPath);
 fill('#construction-zone [name=name]','UI room');fill('#construction-zone [name=length]','3');fill('#construction-zone [name=width]','2');const roomForm=query('#construction-zone');await submit('#construction-zone');roomForm.requestSubmit();await until(()=>doc.querySelector('[data-zone-edit]'),'Room saved');assert.equal((await objectData()).zones.length,1,'Duplicate room prevented');
 click('[data-zone-edit]');assert.equal(query('#construction-zone [name=length]').value,'3');fill('#construction-zone [name=length]','4');await submit('#construction-zone');await until(()=>doc.querySelector('.construction-row')?.textContent.includes('4 × 2'),'Room edited');
 const zone=(await objectData()).zones[0];fill('#construction-measurement [name=zone_id]',zone.id);fill('#construction-measurement [name=symbol]','opening');fill('#construction-measurement [name=value]','1');await submit('#construction-measurement');await until(()=>doc.querySelector('[data-measure-edit]'),'Measurement saved');
 fill('#construction-quantity [name=zone_id]',zone.id);fill('#construction-quantity [name=title]','UI work');fill('#construction-quantity [name=unit_price]','100');await submit('#construction-quantity');await until(()=>doc.querySelector('[data-quantity-edit]'),'Work saved');let work=(await objectData()).quantities.find(item=>item.title==='UI work');assert.equal(Number(work.quantity),8);await until(()=>query('#construction-quantity').closest('.construction-entry'),'Compact mobile work form');assert.equal(query('#construction-quantity').closest('.construction-entry').open,false);click('[data-quantity-edit]');assert.equal(query('#construction-quantity').closest('.construction-entry').open,true);
 fill('#construction-material [name=parent_work_id]',work.id);fill('#construction-material [name=title]','UI paint');fill('#construction-material [name=consumption_rate]','0.2');fill('#construction-material [name=unit_price]','20');await submit('#construction-material');await until(()=>doc.querySelector('[data-material-edit]'),'Material saved');
 fill('#construction-fact [name=quantity_id]',work.id);fill('#construction-fact [name=quantity]','1');await submit('#construction-fact');await until(()=>!query('#construction-act').disabled,'Actual quantity saved');
 click('#construction-price-all');fill('#construction-prices [name=percent]','10');await submit('#construction-prices');await until(()=>doc.querySelector('#construction-price-apply'),'Price preview');click('#construction-price-apply');await until(()=>doc.querySelector('#construction-price-undo'),'Apply prices');assert.equal((await objectData()).quantities.find(item=>item.id===work.id).unit_price,11000);click('#construction-price-undo');await until(()=>!doc.querySelector('#construction-price-undo'),'Undo prices');assert.equal((await objectData()).quantities.find(item=>item.id===work.id).unit_price,10000);
 fill('#construction-defect [name=description]','UI defect');await submit('#construction-defect');await until(()=>doc.querySelector('[data-defect-status]'),'Defect saved');fill('[data-defect-status]','resolved');await until(()=>query('[data-defect-status]').value==='resolved'&&query('#construction-defect [name=description]').value==='','Defect status');
 fill('#construction-log [name=work_description]','UI daily log');fill('#construction-log [name=worker_count]','2');await submit('#construction-log');await until(()=>doc.querySelector('[data-log-edit]'),'Log saved');click('[data-log-edit]');assert.equal(query('#construction-log [name=work_description]').value,'UI daily log');click('#construction-log-cancel');assert.equal(query('#construction-log').dataset.edit,undefined);
 fill('#construction-supplier [name=name]','UI supplier');await submit('#construction-supplier');await until(()=>[...query('#construction-purchase [name=supplier_id]').options].some(item=>item.textContent==='UI supplier'),'Supplier saved');
 const material=(await objectData()).quantities.find(item=>item.kind==='material');fill('#construction-purchase [name=material_id]',material.id);fill('#construction-purchase [name=quantity]','1');fill('#construction-purchase [name=unit_price]','20');await submit('#construction-purchase');await until(()=>doc.querySelector('[data-purchase-edit]'),'Purchase saved');await until(()=>query('#construction-purchase').closest('.construction-entry'),'Compact purchase form');click('[data-purchase-edit]');assert.equal(query('#construction-purchase').closest('.construction-entry').open,true);click('#construction-purchase-cancel');assert.equal(query('#construction-purchase').dataset.edit,undefined);
 for(const selector of ['#construction-export','#construction-report','#construction-act']){const count=downloads.length;click(selector);await until(()=>downloads.length>count,'Download '+selector);const bytes=new Uint8Array(await downloads.at(-1).arrayBuffer());assert.equal(String.fromCharCode(...bytes.slice(0,selector==='#construction-export'?2:4)),selector==='#construction-export'?'PK':'%PDF')}
 click('#construction-change-add');assert.equal(doc.querySelectorAll('.construction-change-line').length,2);click('[data-change-remove]');assert.equal(doc.querySelectorAll('.construction-change-line').length,1);fill('#construction-change [name=title]','UI extras');fill('#construction-change [name=deadline_days]','5');fill('#construction-change-lines [name=name]','UI extra work');fill('#construction-change-lines [name=quantity]','1');fill('#construction-change-lines [name=price]','10');await submit('#construction-change');await until(()=>doc.querySelector('[data-change-send]'),'Extras saved');w.confirm=()=>true;click('[data-change-send]');await until(()=>doc.querySelector('[data-change-link]'),'Send extras');click('[data-change-link]');await until(()=>clipboard.includes('/change.html?token='),'Copy extras URL');click('[data-change-revoke]');await until(()=>!doc.querySelector('[data-change-link]'),'Revoke extras URL');w.confirm=()=>false;
 click('#construction-quote');await until(()=>doc.querySelector('#construction-quote-open'),'Object quote');assert.ok((await objectData()).object.quote_id);click('#construction-quote-open');await until(()=>doc.querySelector('#quote-controls'),'Object quote navigation');
 console.log('PASS: object, room edit, measurement, work/material, fact, price apply/undo, defects, daily log, suppliers, purchases, XLSX/PDF, extras and quote');
 click('#logout');await until(()=>!doc.querySelector('#auth').classList.contains('hidden'),'Logout');
 fill('#email','android-design@test.invalid');fill('#password','android design test only');click('#auth-submit');await until(()=>doc.querySelector('[data-work=quote-new]'),'Login again');await visit('settings');w.confirm=()=>true;click('#delete-account');await until(()=>!doc.querySelector('#auth').classList.contains('hidden'),'Account deleted');await assert.rejects(()=>w.api('/me'),error=>error.status===401);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'app-actions.json'),JSON.stringify(actions,null,2));console.log('PASS:',actions.length,'button/form interactions; isolated real API; no JavaScript errors');
})().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>{clearTimeout(watchdog);dom?.window.close();child.kill();serverLog.end()});
